Repository newfold-labs/wp-module-onboarding, pull requests merged in 2022-08, with the labels that each got.

#50 add/PRESS2-84 Basic Info Page updates
  src/OnboardingSPA/components/MiniPreview/index.js
  src/OnboardingSPA/components/MiniPreview/stylesheet.scss
  src/OnboardingSPA/pages/Steps/BasicInfo/basicInfoForm.js
  src/OnboardingSPA/static/icons/social/instagram-colored.svg
  src/OnboardingSPA/static/icons/social/linkedin-colored.svg
  src/OnboardingSPA/static/icons/social/tiktok-colored.svg
  src/OnboardingSPA/static/icons/social/yelp-colored.svg
  src/OnboardingSPA/static/icons/social/youtube-colored.svg
  src/OnboardingSPA/styles/_icons.scss
Labels: needs-code-improvement

#39 Ecommerce Onbaording flows for Tax Info, Store Address and Products
  includes/Data/Flows.php
  includes/Data/Plugins.php
  src/OnboardingSPA/components/App/index.js
  src/OnboardingSPA/components/NewfoldLargeCard/index.js
  src/OnboardingSPA/data/routes/ecommerce-flow.js
  src/OnboardingSPA/pages/Steps/Ecommerce/StepAddress/index.js
  src/OnboardingSPA/pages/Steps/Ecommerce/StepProducts/index.js
  src/OnboardingSPA/pages/Steps/Ecommerce/StepTax/index.js
  src/OnboardingSPA/pages/Steps/Ecommerce/content.json
  src/OnboardingSPA/pages/Steps/Ecommerce/countries.json
  src/OnboardingSPA/pages/Steps/Ecommerce/stylesheet.scss
  src/OnboardingSPA/pages/Steps/Ecommerce/useWPSettings.js
  src/OnboardingSPA/styles/app.scss
  src/OnboardingSPA/utils/api/ecommerce.js
Labels: needs-code-improvement

#38 PRESS2-57 Removed V1.0 features
  includes/Data/Flows.php
  includes/Data/Options.php
  includes/LoginRedirect.php
  includes/RestApi/FlowController.php
  includes/WP_Config.php
  src/OnboardingSPA/components/ExitToWordPress/index.js
  src/OnboardingSPA/components/Header/step-navigation.js
  src/OnboardingSPA/components/SkipButton/index.js
  src/OnboardingSPA/components/SkipButton/stylesheet.scss
  src/OnboardingSPA/data/routes/default-flow.js
  src/OnboardingSPA/data/sidebars/index.js
  src/OnboardingSPA/index.js
  src/OnboardingSPA/pages/Steps/BasicInfo/basicInfoForm.js
  src/OnboardingSPA/pages/Steps/BasicInfo/stylesheet.scss
  src/OnboardingSPA/pages/Steps/TopPriority/index.js
  src/OnboardingSPA/pages/Steps/TopPriority/stylesheet.scss
  src/OnboardingSPA/styles/app.scss
  src/constants.js
Labels: ecommerce-launch

#62 Removed Default Values for site types
  build/0.0.9/16.js
  build/0.0.9/187.js
  build/0.0.9/220.js
  build/0.0.9/225.js
  build/0.0.9/253.js
  build/0.0.9/257.js
  build/0.0.9/282.js
  build/0.0.9/331.js
  build/0.0.9/376.js
  build/0.0.9/437.js
  build/0.0.9/441.js
  build/0.0.9/527.js
  build/0.0.9/552.js
  build/0.0.9/567.js
  build/0.0.9/577.js
  build/0.0.9/58.js
  build/0.0.9/669.js
  build/0.0.9/69.js
  build/0.0.9/800.js
  build/0.0.9/858.js
  build/0.0.9/867.js
  build/0.0.9/880.js
  build/0.0.9/888.js
  build/0.0.9/978.js
  build/0.0.9/993.js
  build/0.0.9/images/content.1a21aab0.png
  build/0.0.9/images/design.08e4d9fe.png
  build/0.0.9/images/features.84032f3d.png
  build/0.0.9/onboarding.asset.php
  build/0.0.9/onboarding.css
  build/0.0.9/onboarding.js
  includes/Data/Flows.php
  src/OnboardingSPA/pages/Steps/GetStarted/SiteTypeSetup/PrimarySite/index.js
  src/OnboardingSPA/pages/Steps/GetStarted/SiteTypeSetup/SecondarySite/index.js
Labels: bug
