Repository newfold-labs/wp-module-onboarding, pull requests merged in 2023-08, with the labels that each got.

#275 Refactor Analytics
  includes/Data/Events.php
  src/OnboardingSPA/components/App/index.js
  src/OnboardingSPA/components/Button/NavCardButton/index.js
  src/OnboardingSPA/components/Drawer/DrawerPanel/DesignColors.js
  src/OnboardingSPA/components/Drawer/DrawerPanel/DesignHeaderMenu.js
  src/OnboardingSPA/components/Drawer/DrawerPanel/DesignThemeStylesPreview.js
  src/OnboardingSPA/components/Drawer/DrawerPanel/DesignTypography.js
  src/OnboardingSPA/components/ExitToWordPress/index.js
  src/OnboardingSPA/components/Header/step-navigation.js
  src/OnboardingSPA/components/Layouts/Base.js
  src/OnboardingSPA/components/Sidebar/components/LearnMore/Menu.js
  src/OnboardingSPA/components/Sidebar/components/LearnMore/Sidebar.js
  src/OnboardingSPA/components/SkipButton/index.js
  src/OnboardingSPA/components/SocialMediaForm/utils.js
  src/OnboardingSPA/data/routes/default-flow.js
  src/OnboardingSPA/data/routes/ecommerce-flow.js
  src/OnboardingSPA/pages/Steps/DesignHomepageMenu/index.js
  src/OnboardingSPA/pages/Steps/DesignThemeStyles/Menu/index.js
  src/OnboardingSPA/pages/Steps/DesignThemeStyles/Preview/index.js
  src/OnboardingSPA/pages/Steps/Ecommerce/StepTax/index.js
  src/OnboardingSPA/pages/Steps/GetStarted/GetStartedExperience/contents.js
  src/OnboardingSPA/pages/Steps/GetStarted/GetStartedExperience/index.js
  src/OnboardingSPA/pages/Steps/GetStarted/SiteTypeSetup/PrimarySite/index.js
  src/OnboardingSPA/pages/Steps/GetStarted/SiteTypeSetup/SecondarySite/index.js
  src/OnboardingSPA/pages/Steps/SiteFeatures/index.js
  src/OnboardingSPA/pages/Steps/TopPriority/index.js
  src/OnboardingSPA/store/actions.js
  src/OnboardingSPA/store/reducer.js
  src/OnboardingSPA/store/selectors.js
  src/OnboardingSPA/utils/analytics/hiive/OnboardingEvent.js
  src/OnboardingSPA/utils/analytics/hiive/constants.js
  src/OnboardingSPA/utils/analytics/hiive/index.js
  src/OnboardingSPA/utils/analytics/index.js
  src/OnboardingSPA/utils/index.js
  src/constants.js
  src/onboarding.js
Labels: QA

#273 Update PHP dependencies via Composer
  composer.json
  composer.lock
Labels: QA

#276 Remove Tax Step from ecom flow
  src/OnboardingSPA/components/App/index.js
  src/OnboardingSPA/data/routes/ecommerce-flow.js
  src/OnboardingSPA/pages/Steps/Ecommerce/StepAddress/index.js
Labels: Code Review

#277 Enable primary site flow for all customers
  includes/Services/FlowService.php
  src/OnboardingSPA/data/routes/ecommerce-flow.js
  src/OnboardingSPA/pages/Steps/GetStarted/SiteTypeSetup/SecondarySite/index.js
Labels: Code Review

#272 Add Support for WordPress 6.3
  includes/Compatibility/Scan.php
  includes/WP_Admin.php
  src/OnboardingSPA/components/LivePreview/BlockPreview/auto.js
  src/OnboardingSPA/components/LivePreview/BlockPreview/index.js
  src/OnboardingSPA/utils/global-styles/use-global-styles-output.js
Labels: Code Review

#281 Bump PHP to 8.1 in Lint Workflow
  .github/workflows/lint-check-php.yml
Labels: Code Review

#279 Add refer while redirecting from Onboarding to WordPress
  composer.lock
  includes/Data/Brands.php
  src/constants.js
Labels: Code Review

#282 Fix primary type not reflecting in wonder blocks for commerce
  includes/Services/FlowService.php
Labels: Code Review

#280 Handle Plugin Activations to prevent hijack of flow
  includes/Data/Plugins.php
  includes/Data/SiteFeatures.php
  includes/RestApi/PluginsController.php
  includes/RestApi/Themes/ThemeInstallerController.php
  includes/Services/PluginService.php
  includes/Services/ThemeService.php
  includes/WP_Admin.php
  src/OnboardingSPA/components/Button/NavCardButton/index.js
  src/OnboardingSPA/components/Header/step-navigation.js
  src/OnboardingSPA/pages/Steps/Complete/index.js
  src/OnboardingSPA/utils/api/plugins.js
Labels: Code Review

#259 PRESS 2 990 Enhance social media validation
  src/OnboardingSPA/components/ErrorModal/ErrorModal.js
  src/OnboardingSPA/components/ErrorModal/stylesheet.scss
  src/OnboardingSPA/components/Header/step-navigation.js
  src/OnboardingSPA/components/MiniPreview/index.js
  src/OnboardingSPA/components/SocialMediaForm/contents.js
  src/OnboardingSPA/components/SocialMediaForm/index.js
  src/OnboardingSPA/components/SocialMediaForm/urlValidator.js
  src/OnboardingSPA/components/SocialMediaForm/utils.js
  src/OnboardingSPA/components/Tooltip/stylesheet.scss
  src/OnboardingSPA/pages/Steps/BasicInfo/basicInfoForm.js
  src/OnboardingSPA/store/actions.js
  src/OnboardingSPA/store/reducer.js
  src/OnboardingSPA/store/selectors.js
  src/OnboardingSPA/styles/app.scss
Labels: Ready to merge
