Repository newfold-labs/wp-module-onboarding, pull requests merged in 2023-06, with the labels that each got.

#240 Implement Analytics
  .github/workflows/lint-check-spa.yml
  includes/Data/Events.php
  includes/RestApi/EventsController.php
  includes/Services/EventService.php
  package.json
  src/OnboardingSPA/components/App/index.js
  src/OnboardingSPA/components/Drawer/DrawerPanel/DesignColors.js
  src/OnboardingSPA/components/Drawer/DrawerPanel/DesignHeaderMenu.js
  src/OnboardingSPA/components/Drawer/DrawerPanel/DesignThemeStylesPreview.js
  src/OnboardingSPA/components/Drawer/DrawerPanel/DesignTypography.js
  src/OnboardingSPA/components/ExitToWordPress/index.js
  src/OnboardingSPA/components/Layouts/Base.js
  src/OnboardingSPA/components/Sidebar/components/LearnMore/Menu.js
  src/OnboardingSPA/components/Sidebar/components/LearnMore/Sidebar.js
  src/OnboardingSPA/components/SkipButton/index.js
  src/OnboardingSPA/components/StateHandlers/Ecommerce/index.js
  src/OnboardingSPA/pages/Steps/DesignHomepageMenu/index.js
  src/OnboardingSPA/pages/Steps/DesignThemeStyles/Menu/index.js
  src/OnboardingSPA/pages/Steps/DesignThemeStyles/Preview/index.js
  src/OnboardingSPA/pages/Steps/Ecommerce/StepTax/index.js
  src/OnboardingSPA/pages/Steps/GetStarted/GetStartedExperience/index.js
  src/OnboardingSPA/pages/Steps/GetStarted/SiteTypeSetup/PrimarySite/index.js
  src/OnboardingSPA/pages/Steps/GetStarted/SiteTypeSetup/SecondarySite/index.js
  src/OnboardingSPA/pages/Steps/TopPriority/index.js
  src/OnboardingSPA/utils/analytics/index.js
  src/OnboardingSPA/utils/api/events.js
  src/constants.js
  src/onboarding.js
Labels: QA

#247 Fix primary site type width and some clamps
  src/OnboardingSPA/components/Button/NavCardButton/stylesheet.scss
  src/OnboardingSPA/components/CardHeader/stylesheet.scss
  src/OnboardingSPA/pages/Steps/GetStarted/GetStartedExperience/stylesheet.scss
  src/OnboardingSPA/pages/Steps/GetStarted/SiteTypeSetup/PrimarySite/stylesheet.scss
Labels: Ready to merge

#244 Refactor onboarding to use the installer module
  composer.json
  composer.lock
  includes/Application.php
  includes/Data/Data.php
  includes/Data/Flows.php
  includes/Data/Options.php
  includes/Data/Plugins.php
  includes/Data/Preview.php
  includes/Data/Themes.php
  includes/Models/PriorityQueue.php
  includes/Mustache/Templates/aboutPage.mustache
  includes/Mustache/Templates/contactPage.mustache
  includes/Mustache/Templates/homePage.mustache
  includes/Permissions.php
  includes/RestApi/PluginsController.php
  includes/RestApi/Themes/ThemeInstallerController.php
  includes/Services/FlowService.php
  includes/Services/PluginInstaller.php
  includes/Services/PluginService.php
  includes/Services/PluginUninstaller.php
  includes/Services/ThemeInstaller.php
  includes/Services/ThemeService.php
  includes/TaskManagers/PluginInstallTaskManager.php
  includes/TaskManagers/PluginUninstallTaskManager.php
  includes/TaskManagers/TaskManager.php
  includes/TaskManagers/ThemeInstallTaskManager.php
  includes/Tasks/PluginInstallTask.php
  includes/Tasks/PluginUninstallTask.php
  includes/Tasks/Task.php
  includes/Tasks/ThemeInstallTask.php
  includes/WP_Admin.php
  src/OnboardingSPA/utils/api/common.js
  src/OnboardingSPA/utils/api/plugins.js
  src/OnboardingSPA/utils/api/themes.js
  src/constants.js
Labels: Code Review

#248 Remove unused import
  src/OnboardingSPA/utils/api/plugins.js
Labels: Ready to merge

#230 Enhance/make flow data robust
  composer.json
  composer.lock
  includes/Data/Data.php
  includes/Data/Flows/Flows.php
  includes/Data/Flows/Upgrades/1.0.0.php
  includes/ModuleController.php
  includes/RestApi/FlowController.php
  includes/RestApi/Themes/ThemeGeneratorController.php
  includes/Services/FlowService.php
  includes/WP_Admin.php
  src/OnboardingSPA/components/Drawer/DrawerPanel/DesignColors.js
  src/OnboardingSPA/components/Drawer/DrawerPanel/DesignTypography.js
  src/OnboardingSPA/components/ImageUploader/index.js
  src/OnboardingSPA/components/MiniPreview/contents.js
  src/OnboardingSPA/components/MiniPreview/index.js
  src/OnboardingSPA/index.js
  src/OnboardingSPA/pages/Steps/BasicInfo/basicInfoForm.js
Labels: Ready to merge

#246 removed hard coded slugs from header menu step
  includes/Data/Patterns.php
  src/OnboardingSPA/components/Drawer/DrawerPanel/DesignHeaderMenu.js
Labels: QA

#252 PRESS-2 982 | Remove unused images
  src/OnboardingSPA/components/CheckboxTemplate/CheckboxItem/index.js
  src/OnboardingSPA/components/MiniPreview/index.js
  src/OnboardingSPA/components/SocialMediaForm/stylesheet.scss
  src/OnboardingSPA/static/icons/business-white.svg
  src/OnboardingSPA/static/icons/business.svg
  src/OnboardingSPA/static/icons/creative-white.svg
  src/OnboardingSPA/static/icons/creative.svg
  src/OnboardingSPA/static/icons/dog-white.svg
  src/OnboardingSPA/static/icons/dog.svg
  src/OnboardingSPA/static/icons/education-white.svg
  src/OnboardingSPA/static/icons/education.svg
  src/OnboardingSPA/static/icons/entertainment-white.svg
  src/OnboardingSPA/static/icons/entertainment.svg
  src/OnboardingSPA/static/icons/food-white.svg
  src/OnboardingSPA/static/icons/food.svg
  src/OnboardingSPA/static/icons/group-team-white.svg
  src/OnboardingSPA/static/icons/group-team.svg
  src/OnboardingSPA/static/icons/health-white.svg
  src/OnboardingSPA/static/icons/health.svg
  src/OnboardingSPA/static/icons/heart-white.svg
  src/OnboardingSPA/static/icons/heart.svg
  src/OnboardingSPA/static/icons/news-white.svg
  src/OnboardingSPA/static/icons/news.svg
  src/OnboardingSPA/static/icons/politics-white.svg
  src/OnboardingSPA/static/icons/politics.svg
  src/OnboardingSPA/static/icons/site-features/analytics_light.svg
  src/OnboardingSPA/static/icons/site-features/bookingcalendar_light.svg
  src/OnboardingSPA/static/icons/site-features/email_light.svg
  src/OnboardingSPA/static/icons/site-features/filter_light.svg
  src/OnboardingSPA/static/icons/site-features/form_light.svg
  src/OnboardingSPA/static/icons/site-features/lead_light.svg
  src/OnboardingSPA/static/icons/site-features/search_light.svg
  src/OnboardingSPA/static/icons/site-features/security_light.svg
  src/OnboardingSPA/static/icons/site-features/share_light.svg
  src/OnboardingSPA/static/icons/site-features/wishlist_light.svg
  src/OnboardingSPA/static/icons/social/facebook-colored.svg
  src/OnboardingSPA/static/icons/social/facebook.svg
  src/OnboardingSPA/static/icons/social/instagram-colored.svg
  src/OnboardingSPA/static/icons/social/instagram.svg
  src/OnboardingSPA/static/icons/social/linkedin-colored.svg
  src/OnboardingSPA/static/icons/social/linkedin.svg
  src/OnboardingSPA/static/icons/social/tiktok-colored.svg
  src/OnboardingSPA/static/icons/social/tiktok.svg
  src/OnboardingSPA/static/icons/social/twitter-colored.svg
  src/OnboardingSPA/static/icons/social/twitter.svg
  src/OnboardingSPA/static/icons/social/yelp-colored.svg
  src/OnboardingSPA/static/icons/social/yelp.svg
  src/OnboardingSPA/static/icons/social/youtube-colored.svg
  src/OnboardingSPA/static/icons/social/youtube.svg
  src/OnboardingSPA/static/icons/tech-white.svg
  src/OnboardingSPA/static/icons/tech.svg
  src/OnboardingSPA/styles/_icons.scss
Labels: Ready to merge

#256 Remove all dategating and rely on coming soon
  includes/Compatibility/Safe_Mode.php
  includes/Data/Brands.php
  includes/Data/Data.php
  includes/Data/Options.php
  includes/LoginRedirect.php
  includes/ModuleController.php
Labels: QA

#255 Add `page` to pageview events
  includes/Compatibility/Safe_Mode.php
  includes/Data/Brands.php
  includes/Data/Data.php
  includes/Data/Options.php
  includes/LoginRedirect.php
  includes/ModuleController.php
  src/OnboardingSPA/utils/analytics/index.js
Labels: QA

#251 Palette Mapping and Custom to Predefined Palette fix
  src/OnboardingSPA/components/Drawer/DrawerPanel/DesignColors.js
Labels: Ready to merge

#261 Fix newfold card logo popping up on safari
  src/OnboardingSPA/components/NewfoldLargeCard/index.js
  src/OnboardingSPA/components/NewfoldLargeCard/stylesheet.scss
Labels: QA

#258 Add name spacing to analytics events
  package-lock.json
  package.json
  src/OnboardingSPA/components/App/index.js
  src/OnboardingSPA/components/ExitToWordPress/index.js
  src/OnboardingSPA/components/SkipButton/index.js
  src/OnboardingSPA/utils/analytics/index.js
  src/onboarding.js
Labels: Ready to merge
