Repository newfold-labs/wp-module-onboarding, pull requests merged in 2023-05, with the labels that each got.

#220 Implement Site Classification API (Backend Controller)
  includes/RestApi/RestApi.php
  includes/RestApi/SiteClassificationController.php
Labels: Ready to merge

#222 PRESS-2 793 Add Custom Design Bypass
  src/OnboardingSPA/components/HeadingWithSubHeading/index.js
  src/OnboardingSPA/data/routes/default-flow.js
  src/OnboardingSPA/pages/Steps/DesignThemeStyles/Menu/index.js
  src/OnboardingSPA/pages/Steps/DesignThemeStyles/Menu/stylesheet.scss
  src/OnboardingSPA/pages/Steps/DesignThemeStyles/Preview/index.js
  src/OnboardingSPA/pages/Steps/DesignThemeStyles/contents.js
  src/OnboardingSPA/pages/Steps/DesignThemeStyles/utils.js
Labels: Ready to merge

#225 Remove unnecessary redirect transient update
  includes/ModuleController.php
Labels: Ready to merge

#227 Fix typography live preview not reflecting previous selections on refresh
  src/OnboardingSPA/components/Drawer/DrawerPanel/DesignTypography.js
Labels: Ready to merge

#231 Add redirect for SSO logins
  includes/Application.php
  includes/LoginRedirect.php
Labels: Code Review

#228 Enhance preview step to auto advance on custom design checkbox selection
  src/OnboardingSPA/pages/Steps/DesignThemeStyles/Preview/index.js
Labels: Ready to merge

#229 PRESS-2 761 - Implement Interface Skeleton
  src/OnboardingSPA/components/App/index.js
  src/OnboardingSPA/components/NewfoldInterfaceSkeleton/index.js
  src/OnboardingSPA/components/NewfoldInterfaceSkeleton/style.scss
  src/OnboardingSPA/styles/app.scss
Labels: Ready to merge

#237 Update primary and secondary type data using helpers from the data module
  includes/RestApi/FlowController.php
  includes/RestApi/SiteClassificationController.php
Labels: Code Review

#221 PRESS-2 834 Implement Site Classification API (Frontend)
  includes/Data/Flows.php
  includes/RestApi/FlowController.php
  src/OnboardingSPA/pages/Steps/GetStarted/SiteTypeSetup/PrimarySite/index.js
  src/OnboardingSPA/pages/Steps/GetStarted/SiteTypeSetup/PrimarySite/stylesheet.scss
  src/OnboardingSPA/pages/Steps/GetStarted/SiteTypeSetup/SecondarySite/index.js
  src/OnboardingSPA/pages/Steps/GetStarted/SiteTypeSetup/SecondarySite/stylesheet.scss
  src/OnboardingSPA/pages/Steps/GetStarted/SiteTypeSetup/content.json
  src/OnboardingSPA/pages/Steps/GetStarted/SiteTypeSetup/contents.js
  src/OnboardingSPA/utils/api/siteClassification.js
  src/OnboardingSPA/utils/api/siteClassification.json
Labels: QA

#226 Add support for translations in the React SPA
  src/OnboardingSPA/components/MiniPreview/contents.js
  src/OnboardingSPA/components/MiniPreview/index.js
  src/OnboardingSPA/components/MiniPreview/miniPreview.json
  src/OnboardingSPA/components/MiniPreview/stylesheet.scss
  src/OnboardingSPA/data/routes/default-flow.js
  src/OnboardingSPA/pages/Steps/Ecommerce/StepAddress/contents.js
  src/OnboardingSPA/pages/Steps/Ecommerce/StepAddress/index.js
  src/OnboardingSPA/pages/Steps/Ecommerce/StepProducts/contents.js
  src/OnboardingSPA/pages/Steps/Ecommerce/StepProducts/index.js
  src/OnboardingSPA/pages/Steps/Ecommerce/StepTax/contents.js
  src/OnboardingSPA/pages/Steps/Ecommerce/StepTax/index.js
  src/OnboardingSPA/pages/Steps/Ecommerce/content.json
  src/OnboardingSPA/pages/Steps/GetStarted/GetStartedExperience/content.json
  src/OnboardingSPA/pages/Steps/GetStarted/GetStartedExperience/contents.js
  src/OnboardingSPA/pages/Steps/GetStarted/GetStartedExperience/index.js
  src/OnboardingSPA/pages/Steps/GetStarted/SiteTypeSetup/PrimarySite/index.js
  src/OnboardingSPA/pages/Steps/GetStarted/SiteTypeSetup/SecondarySite/index.js
  src/OnboardingSPA/pages/Steps/GetStarted/SiteTypeSetup/contents.js
  src/OnboardingSPA/pages/Steps/GetStarted/Welcome/contents.js
  src/OnboardingSPA/pages/Steps/GetStarted/Welcome/index.js
  src/OnboardingSPA/pages/Steps/GetStarted/Welcome/tabContent.json
  src/OnboardingSPA/pages/Steps/TopPriority/contents.js
  src/OnboardingSPA/pages/Steps/TopPriority/index.js
  src/OnboardingSPA/pages/Steps/TopPriority/stylesheet.scss
  src/OnboardingSPA/styles/_interface.scss
Labels: Ready to merge

#213 Replace hex and RGB values
  src/OnboardingSPA/components/Accordion/stylesheet.scss
  src/OnboardingSPA/components/App/index.js
  src/OnboardingSPA/components/Button/ButtonBlue/stylesheet.scss
  src/OnboardingSPA/components/Button/ButtonWhite/stylesheet.scss
  src/OnboardingSPA/components/CheckboxTemplate/CheckboxItem/stylesheet.scss
  src/OnboardingSPA/components/CheckboxTemplate/CheckboxListSkeleton/stylesheet.scss
  src/OnboardingSPA/components/Content/stylesheet.scss
  src/OnboardingSPA/components/Drawer/stylesheet.scss
  src/OnboardingSPA/components/Header/stylesheet.scss
  src/OnboardingSPA/components/HeadingWithSubHeading/stylesheet.scss
  src/OnboardingSPA/components/LivePreview/BlockPreview/stylesheet.scss
  src/OnboardingSPA/components/LivePreview/SelectableCard/stylesheet.scss
  src/OnboardingSPA/components/LivePreview/SelectableCardWithInfo/index.js
  src/OnboardingSPA/components/LivePreview/SelectableCardWithInfo/stylesheet.scss
  src/OnboardingSPA/components/MiniPreview/stylesheet.scss
  src/OnboardingSPA/components/NeedHelpTag/stylesheet.scss
  src/OnboardingSPA/components/NewfoldLargeCard/stylesheet.scss
  src/OnboardingSPA/components/SelectableCard/stylesheet.scss
  src/OnboardingSPA/components/Sidebar/components/LearnMore/Skeleton/stylesheet.scss
  src/OnboardingSPA/components/StepOverview/stylesheet.scss
  src/OnboardingSPA/components/TextInput/stylesheet.scss
  src/OnboardingSPA/components/Tooltip/stylesheet.scss
  src/OnboardingSPA/pages/Steps/DesignColors/stylesheet.scss
  src/OnboardingSPA/pages/Steps/DesignHeaderMenu/stylesheet.scss
  src/OnboardingSPA/pages/Steps/DesignHomepageMenu/stylesheet.scss
  src/OnboardingSPA/pages/Steps/DesignThemeStyles/Menu/stylesheet.scss
  src/OnboardingSPA/pages/Steps/DesignThemeStyles/Preview/stylesheet.scss
  src/OnboardingSPA/pages/Steps/DesignTypography/stylesheet.scss
  src/OnboardingSPA/pages/Steps/GetStarted/GetStartedExperience/stylesheet.scss
  src/OnboardingSPA/pages/Steps/GetStarted/SiteTypeSetup/PrimarySite/stylesheet.scss
  src/OnboardingSPA/pages/Steps/GetStarted/SiteTypeSetup/SecondarySite/stylesheet.scss
  src/OnboardingSPA/pages/Steps/GetStarted/Welcome/stylesheet.scss
  src/OnboardingSPA/pages/Steps/WhatNext/stylesheet.scss
  src/OnboardingSPA/styles/_branding.scss
  src/OnboardingSPA/styles/_interface.scss
  src/OnboardingSPA/styles/_utilities.scss
  src/OnboardingSPA/styles/app.scss
Labels: Ready to merge

#233 PRESS-2 494 Audit react-router-dom
  package.json
Labels: Ready to merge

#235 Optimize useGlobalStylesOutput and LivePreview usage
  src/OnboardingSPA/components/Drawer/DrawerPanel/DesignColors.js
  src/OnboardingSPA/components/Drawer/DrawerPanel/DesignHeaderMenu.js
  src/OnboardingSPA/components/Drawer/DrawerPanel/DesignThemeStylesPreview.js
  src/OnboardingSPA/components/Drawer/DrawerPanel/DesignTypography.js
  src/OnboardingSPA/components/LivePreview/BlockPreview/auto.js
  src/OnboardingSPA/components/LivePreview/BlockPreview/index.js
  src/OnboardingSPA/components/LivePreview/GlobalStylesProvider/index.js
  src/OnboardingSPA/components/LivePreview/LivePreviewSkeleton/index.js
  src/OnboardingSPA/pages/Steps/DesignColors/index.js
  src/OnboardingSPA/pages/Steps/DesignHeaderMenu/index.js
  src/OnboardingSPA/pages/Steps/DesignHomepageMenu/index.js
  src/OnboardingSPA/pages/Steps/DesignThemeStyles/Menu/index.js
  src/OnboardingSPA/pages/Steps/DesignThemeStyles/Preview/index.js
  src/OnboardingSPA/pages/Steps/DesignTypography/index.js
  src/OnboardingSPA/pages/Steps/SitePages/index.js
Labels: Ready to merge

#241 Fix custom color selections not reflecting in the accordion
  src/OnboardingSPA/components/Drawer/DrawerPanel/DesignColors.js
Labels: Code Review

#236 refactored hard coded logic from homepage menu
  includes/Data/Patterns.php
  src/OnboardingSPA/pages/Steps/DesignHomepageMenu/index.js
Labels: Ready to merge

#238 PHP Lint fixes
  includes/Data/Brands.php
  includes/Data/Events.php
  includes/Data/Flows.php
  includes/Data/Options.php
  includes/Data/Themes/Colors.php
  includes/Data/Themes/Fonts.php
  includes/LoginRedirect.php
  includes/Models/PriorityQueue.php
  includes/Models/Theme.php
  includes/ModuleController.php
  includes/Mustache/Mustache.php
  includes/Permissions.php
  includes/RestApi/BaseHiiveController.php
  includes/RestApi/EventsController.php
  includes/RestApi/PluginsController.php
  includes/RestApi/RestApiFilter.php
  includes/RestApi/SiteImagesController.php
  includes/RestApi/Themes/PatternsController.php
  includes/RestApi/Themes/ThemeVariationsController.php
  includes/Services/FlowService.php
  includes/Services/PluginUninstaller.php
  includes/Services/ThemeInstaller.php
  includes/TaskManagers/PluginUninstallTaskManager.php
  includes/TaskManagers/TaskManager.php
  includes/TaskManagers/ThemeInstallTaskManager.php
  includes/Tasks/PluginInstallTask.php
  includes/Tasks/PluginUninstallTask.php
  includes/Tasks/ThemeInstallTask.php
  includes/WP_Admin.php
  includes/WP_CLI.php
  includes/WP_Config.php
Labels: Ready to merge

#239 PRESS-2 567 Aspect Ratio driven sizing of site logo
  includes/RestApi/RestApiFilter.php
Labels: Ready to merge

#243 Add enablement query param
  includes/Data/Options.php
  includes/ModuleController.php
Labels: Ready to merge
