Repository newfold-labs/wp-module-onboarding, pull requests merged in 2023-09, with the labels that each got.

#291 Fix Safari ordering issue
  src/OnboardingSPA/pages/Steps/DesignThemeStyles/Menu/index.js
  src/OnboardingSPA/pages/Steps/DesignThemeStyles/Menu/stylesheet.scss
  src/OnboardingSPA/styles/_utilities.scss
Labels: Ready to merge

#294 Change Generated Site's Title Homepage to Home
  includes/RestApi/SitePagesController.php
  languages/wp-module-onboarding.pot
Labels: QA

#292 Adding Cypress Tests to module
  tests/cypress/fixtures/image.png
  tests/cypress/integration/1-Initial-steps/branding.cy.js
  tests/cypress/integration/1-Initial-steps/whats-next.cy.js
  tests/cypress/integration/2-general-onboarding-flow/basic-info.cy.js
  tests/cypress/integration/2-general-onboarding-flow/exit-to-wordpress.cy.js
  tests/cypress/integration/2-general-onboarding-flow/get-started-experience.cy.js
  tests/cypress/integration/2-general-onboarding-flow/get-started-welcome.cy.js
  tests/cypress/integration/2-general-onboarding-flow/site-features.cy.js
  tests/cypress/integration/2-general-onboarding-flow/sitetype-primary.cy.js
  tests/cypress/integration/2-general-onboarding-flow/sitetype-secondary.cy.js
  tests/cypress/integration/2-general-onboarding-flow/top-priority.cy.js
  tests/cypress/integration/3-ecommerce-onboarding-flow/address.cy.js
  tests/cypress/integration/3-ecommerce-onboarding-flow/basic-info.cy.js
  tests/cypress/integration/3-ecommerce-onboarding-flow/exit-to-wordpress.cy.js
  tests/cypress/integration/3-ecommerce-onboarding-flow/get-started-experience.cy.js
  tests/cypress/integration/3-ecommerce-onboarding-flow/get-started-welcome.cy.js
  tests/cypress/integration/3-ecommerce-onboarding-flow/products.cy.js
  tests/cypress/integration/3-ecommerce-onboarding-flow/site-features.cy.js
  tests/cypress/integration/3-ecommerce-onboarding-flow/sitetype-secondary.cy.js
  tests/cypress/integration/3-ecommerce-onboarding-flow/tax-info.cy.js
  tests/cypress/integration/4-design-steps/colors-step.cy.js
  tests/cypress/integration/4-design-steps/continue-onboarding.cy.js
  tests/cypress/integration/4-design-steps/header-menu.cy.js
  tests/cypress/integration/4-design-steps/homepage-styles.cy.js
  tests/cypress/integration/4-design-steps/site-pages.cy.js
  tests/cypress/integration/4-design-steps/theme-styles.cy.js
  tests/cypress/integration/4-design-steps/typography-step.cy.js
  tests/cypress/integration/example.spec.js
  tests/cypress/integration/sidebar.cy.js
  tests/cypress/integration/wp-module-support/drawer.cy.js
  tests/cypress/integration/wp-module-support/header.cy.js
  tests/cypress/integration/wp-module-support/pluginID.cy.js
  tests/cypress/integration/wp-module-support/sidebar.cy.js
Labels: Ready to merge

#300 Add Primary Step cypress tests to ecommerce flow
  tests/cypress/integration/3-ecommerce-onboarding-flow/sitetype-primary.cy.js
Labels: Code Review

#299 Add support for translations in the module
  bootstrap.php
  includes/Application.php
  includes/Services/I18nService.php
  includes/WP_Admin.php
  languages/wp-module-onboarding-pt_BR-nfd-onboarding.json
  languages/wp-module-onboarding-pt_BR.mo
  languages/wp-module-onboarding-pt_BR.po
  src/OnboardingSPA/components/Button/ButtonBlue/stylesheet.scss
  src/OnboardingSPA/components/Button/ButtonWhite/stylesheet.scss
Labels: Ready to merge

#304 Redirect all users to the brand plugin dashboard
  src/OnboardingSPA/components/Button/NavCardButton/index.js
  src/OnboardingSPA/components/ExitToWordPress/index.js
  src/OnboardingSPA/components/Header/step-navigation.js
  src/OnboardingSPA/components/SkipButton/index.js
Labels: Ready to merge

#305 Add Social Media Validation Checks for Basic Info page
  tests/cypress/integration/2-general-onboarding-flow/basic-info.cy.js
  tests/cypress/integration/3-ecommerce-onboarding-flow/basic-info.cy.js
  tests/cypress/integration/wp-module-support/socialMedia.cy.js
Labels: Code Review

#301 Grid Component
  src/OnboardingSPA/components/Grid/index.js
  src/OnboardingSPA/components/Grid/stylesheet.scss
  src/OnboardingSPA/pages/Steps/DesignHomepageMenu/index.js
  src/OnboardingSPA/pages/Steps/DesignThemeStyles/Menu/index.js
  src/OnboardingSPA/pages/Steps/DesignThemeStyles/Menu/stylesheet.scss
  src/OnboardingSPA/pages/Steps/SitePages/index.js
  src/OnboardingSPA/pages/Steps/SitePages/stylesheet.scss
  src/OnboardingSPA/styles/_utilities.scss
  src/OnboardingSPA/styles/app.scss
Labels: Ready to merge

#308 HostGator Support
  composer.lock
  includes/Data/Brands.php
  includes/ModuleController.php
  package-lock.json
  src/Brands/hostgator/step-error-logo.svg
  src/Brands/hostgator/step-loader-logo.svg
  src/OnboardingSPA/components/ImageUploader/index.js
  src/OnboardingSPA/components/MiniPreview/contents.js
  src/OnboardingSPA/components/MiniPreview/index.js
  src/OnboardingSPA/pages/Steps/Ecommerce/StepAddress/index.js
  src/OnboardingSPA/pages/Steps/GetStarted/SiteTypeSetup/PrimarySite/index.js
  src/OnboardingSPA/store/selectors.js
  src/OnboardingSPA/styles/_branding.scss
Labels: Code Review

#307 Release Preparation Workflow
  .github/workflows/prepare-release.yml
  composer.json
  composer.lock
Labels: Ready to merge

#314 Fix GitHub Action deprecated notices.
  .github/workflows/satis-update.yml
Labels: Code Review

#302 Add Defensive checks in Patterns Data class
  includes/Data/Patterns.php
Labels: Ready to merge

#315 Add Migrate Button to Start Setup
  src/OnboardingSPA/components/Button/ButtonWhite/index.js
  src/OnboardingSPA/components/Button/NavCardButton/index.js
  src/OnboardingSPA/components/Button/NavCardButton/stylesheet.scss
  src/OnboardingSPA/steps/GetStarted/Welcome/contents.js
  src/OnboardingSPA/steps/GetStarted/Welcome/index.js
  src/OnboardingSPA/steps/GetStarted/Welcome/stylesheet.scss
  src/OnboardingSPA/steps/WhatNext/stylesheet.scss
  src/OnboardingSPA/store/selectors.js
Labels: Ready to merge

#316 Track Site Features on Step Change
  src/OnboardingSPA/components/App/index.js
  src/OnboardingSPA/steps/SiteFeatures/index.js
Labels: Ready to merge

#317 Update `pt_BR` translations
  languages/wp-module-onboarding-pt_BR-nfd-onboarding.json
  languages/wp-module-onboarding-pt_BR.mo
  languages/wp-module-onboarding-pt_BR.po
Labels: Ready to merge

#318 Return to old flow when prioritization is disabled
  src/OnboardingSPA/components/StateHandlers/Flow/index.js
  src/OnboardingSPA/data/flows/ecommerce.js
Labels: Ready to merge
