Repository newfold-labs/wp-module-onboarding, pull requests merged in 2023-01, with the labels that each got.

#139 Live preview cursor states
  .gitignore
  src/OnboardingSPA/components/CheckboxTemplate/CheckboxListSkeleton/stylesheet.scss
  src/OnboardingSPA/components/LivePreview/BlockPreview/stylesheet.scss
  src/OnboardingSPA/components/LivePreview/SelectableCardWithInfo/index.js
  src/OnboardingSPA/components/LivePreview/SelectableCardWithInfo/stylesheet.scss
  src/OnboardingSPA/pages/Steps/DesignColors/stylesheet.scss
  src/OnboardingSPA/pages/Steps/DesignHeaderMenu/stylesheet.scss
  src/OnboardingSPA/pages/Steps/DesignHomepageMenu/stylesheet.scss
  src/OnboardingSPA/pages/Steps/DesignThemeStyles/Menu/stylesheet.scss
  src/OnboardingSPA/pages/Steps/DesignThemeStyles/Preview/stylesheet.scss
  src/OnboardingSPA/pages/Steps/DesignTypography/stylesheet.scss
  src/OnboardingSPA/pages/Steps/SitePages/stylesheet.scss
Labels: Post Phase 2 Polish

#140 Press 2 470 Improve Social Media capture UI
  src/OnboardingSPA/components/MiniPreview/index.js
  src/OnboardingSPA/components/MiniPreview/stylesheet.scss
  src/OnboardingSPA/components/SocialMediaForm/index.js
  src/OnboardingSPA/pages/Steps/BasicInfo/basicInfoForm.js
Labels: Post Phase 2 Polish

#142 Press 2 474 Generic step loader cursor states
  src/OnboardingSPA/components/Loaders/Step/stylesheet.scss
Labels: Post Phase 2 Polish

#141 Fix tax logic
  src/OnboardingSPA/pages/Steps/Ecommerce/content.json
Labels: bug, Post Phase 2 Polish

#143 Release/v1.0.0 polished
  .gitignore
  src/OnboardingSPA/components/CheckboxTemplate/CheckboxListSkeleton/stylesheet.scss
  src/OnboardingSPA/components/LivePreview/BlockPreview/stylesheet.scss
  src/OnboardingSPA/components/LivePreview/SelectableCardWithInfo/index.js
  src/OnboardingSPA/components/LivePreview/SelectableCardWithInfo/stylesheet.scss
  src/OnboardingSPA/components/Loaders/Step/stylesheet.scss
  src/OnboardingSPA/components/MiniPreview/index.js
  src/OnboardingSPA/components/MiniPreview/stylesheet.scss
  src/OnboardingSPA/components/RadioControl/RadioControlSkeleton/index.js
  src/OnboardingSPA/components/RadioControl/RadioControlSkeleton/stylesheet.scss
  src/OnboardingSPA/components/RadioControl/RadioControlStateHandler/index.js
  src/OnboardingSPA/components/RadioControl/index.js
  src/OnboardingSPA/components/SocialMediaForm/index.js
  src/OnboardingSPA/pages/Steps/BasicInfo/basicInfoForm.js
  src/OnboardingSPA/pages/Steps/DesignColors/stylesheet.scss
  src/OnboardingSPA/pages/Steps/DesignHeaderMenu/stylesheet.scss
  src/OnboardingSPA/pages/Steps/DesignHomepageMenu/stylesheet.scss
  src/OnboardingSPA/pages/Steps/DesignThemeStyles/Menu/stylesheet.scss
  src/OnboardingSPA/pages/Steps/DesignThemeStyles/Preview/stylesheet.scss
  src/OnboardingSPA/pages/Steps/DesignTypography/stylesheet.scss
  src/OnboardingSPA/pages/Steps/Ecommerce/StepTax/Sidebar/LearnMore/contents.js
  src/OnboardingSPA/pages/Steps/Ecommerce/StepTax/Sidebar/LearnMore/index.js
  src/OnboardingSPA/pages/Steps/Ecommerce/StepTax/index.js
  src/OnboardingSPA/pages/Steps/Ecommerce/content.json
  src/OnboardingSPA/pages/Steps/Ecommerce/stylesheet.scss
  src/OnboardingSPA/pages/Steps/GetStarted/GetStartedExperience/Sidebar/LearnMore/contents.js
  src/OnboardingSPA/pages/Steps/GetStarted/GetStartedExperience/Sidebar/LearnMore/index.js
  src/OnboardingSPA/pages/Steps/GetStarted/GetStartedExperience/index.js
  src/OnboardingSPA/pages/Steps/SitePages/stylesheet.scss
  src/OnboardingSPA/styles/app.scss
Labels: Post Phase 2 Polish

#149 Remove trailing commas in function calls.
  includes/Data/Plugins.php
  includes/RestApi/PluginsController.php
  includes/RestApi/Themes/ThemeVariationsController.php
  includes/TaskManagers/PluginUninstallTaskManager.php
Labels: bug

#152 Handle module disabling on prod
  includes/Data/Data.php
Labels: bug

#150 Add PHP code linting
  .github/workflows/lint.yml
  composer.json
  composer.lock
  phpcs.xml
Labels: enhancement

#144 Disable navigation when in loading states
  src/OnboardingSPA/components/StateHandlers/Design/index.js
  src/OnboardingSPA/components/StateHandlers/Ecommerce/index.js
  src/OnboardingSPA/pages/Steps/Complete/index.js
  src/OnboardingSPA/pages/Steps/DesignColors/index.js
  src/OnboardingSPA/pages/Steps/DesignHeaderMenu/index.js
  src/OnboardingSPA/pages/Steps/DesignHomepageMenu/index.js
  src/OnboardingSPA/pages/Steps/DesignThemeStyles/Menu/index.js
  src/OnboardingSPA/pages/Steps/DesignThemeStyles/Preview/index.js
  src/OnboardingSPA/pages/Steps/DesignTypography/index.js
  src/OnboardingSPA/pages/Steps/Ecommerce/StepAddress/index.js
  src/OnboardingSPA/pages/Steps/Ecommerce/StepProducts/index.js
  src/OnboardingSPA/pages/Steps/Ecommerce/StepTax/index.js
  src/OnboardingSPA/pages/Steps/SitePages/index.js
Labels: Post Phase 2 Polish

#153 Fallback to customer data if flow param/option does not exist
  includes/Data/Data.php
  includes/Data/Flows.php
  includes/Data/Options.php
  includes/ModuleController.php
Labels: bug, Post Phase 2 Polish

#145 PRESS 2-462 Loader for Street Address step Ecommerce
  src/OnboardingSPA/components/Animate/index.js
  src/OnboardingSPA/components/Animate/stylesheet.scss
  src/OnboardingSPA/pages/Steps/Ecommerce/StepAddress/index.js
  src/OnboardingSPA/styles/_utilities.scss
  src/OnboardingSPA/styles/app.scss
Labels: Post Phase 2 Polish

#154 Yith Wonder 1.2.0: Adjust Onboarding Colors and Fonts
  includes/Data/Flows.php
  includes/Data/Themes/Colors.php
  src/OnboardingSPA/components/Drawer/DrawerPanel/DesignColors.js
  src/OnboardingSPA/components/Drawer/DrawerPanel/DesignTypography.js
Labels: bug, Post Phase 2 Polish

#146 Basic Info FadeIn State
  src/OnboardingSPA/components/MiniPreview/index.js
  src/OnboardingSPA/components/SocialMediaForm/index.js
  src/OnboardingSPA/pages/Steps/BasicInfo/basicInfoForm.js
Labels: Post Phase 2 Polish

#156 Remove brand-specific mark in illustration
  src/OnboardingSPA/static/icons/learn-more-what-next.svg
Labels: Post Phase 2 Polish

#147 fadein loading state for sitetype steps
  src/OnboardingSPA/pages/Steps/GetStarted/SiteTypeSetup/PrimarySite/index.js
  src/OnboardingSPA/pages/Steps/GetStarted/SiteTypeSetup/SecondarySite/index.js
Labels: Post Phase 2 Polish

#148 altered a few access modifiers and removed unused imports
  includes/Data/Options.php
  includes/Data/Patterns.php
  includes/Data/SiteFeatures.php
  includes/RestApi/FlowController.php
  includes/RestApi/SettingsController.php
  includes/RestApi/SitePagesController.php
  includes/RestApi/Themes/ThemeGeneratorController.php
Labels: Post Phase 2 Polish

#163 Update brand metadata
  includes/Data/Brands.php
Labels: Ready to merge

#160 Refine Learn More sidebars content
  src/OnboardingSPA/pages/Steps/GetStarted/GetStartedExperience/Sidebar/LearnMore/contents.js
  src/OnboardingSPA/pages/Steps/GetStarted/SiteTypeSetup/PrimarySite/Sidebar/LearnMore/contents.js
  src/OnboardingSPA/pages/Steps/GetStarted/SiteTypeSetup/SecondarySite/Sidebar/LearnMore/contents.js
  src/OnboardingSPA/pages/Steps/GetStarted/Welcome/Sidebar/LearnMore/contents.js
  src/OnboardingSPA/pages/Steps/SiteFeatures/Sidebar/LearnMore/contents.js
  src/OnboardingSPA/pages/Steps/WhatNext/Sidebar/LearnMore/contents.js
Labels: Ready to merge

#161 Refine Welcome Tab content
  src/OnboardingSPA/pages/Steps/GetStarted/Welcome/index.js
  src/OnboardingSPA/pages/Steps/GetStarted/Welcome/tabContent.json
Labels: Ready to merge

#159 Step What's Next: Modify bitmap image for better display
  src/OnboardingSPA/static/images/wp-admin.png
Labels: Ready to merge

#162 Propose bump of @wordpress/icons from 8.2.x to 9.16.x
  package-lock.json
  package.json
Labels: Ready to merge
