Repository newfold-labs/wp-module-onboarding, pull requests merged in 2024-03, with the labels that each got.

#499 Enhance AI Generation time
  src/OnboardingSPA/components/Header/components/SiteGenHeader/index.js
  src/OnboardingSPA/components/NewfoldInterfaceSkeleton/SiteGen/index.js
  src/OnboardingSPA/steps/SiteGen/SiteLogo/index.js
Labels: QA

#500 Skip Fork Screen if Sitegen Capability is disabled and fix back button issue
  src/OnboardingSPA/components/Header/components/SiteBuildHeader/step-navigation.js
  src/OnboardingSPA/components/SiteGenError/index.js
  src/OnboardingSPA/components/StartOptions/index.js
  src/OnboardingSPA/components/StateHandlers/Flow/index.js
  src/OnboardingSPA/data/flows/utils.js
  src/OnboardingSPA/steps/TheFork/index.js
Labels: Code Review

#502 Just in case | Fail safe checks
  src/OnboardingSPA/steps/SiteGen/Preview/index.js
Labels: QA

#503 Added fix for deprecated warning from onboarding module.
  includes/WP_Admin.php
Labels: QA

#504 site-details page : extra spaces
  src/OnboardingSPA/components/TextInput/TextInputSiteGen/stylesheet.scss
  src/OnboardingSPA/steps/SiteGen/SiteDetails/stylesheet.scss
Labels: Code Review

#506 Cypress failing tests fix
  .github/workflows/brand-plugin-test.yml
  src/OnboardingSPA/components/StateHandlers/Flow/index.js
  tests/cypress/integration/1-Initial-steps/sidebar.cy.js
  tests/cypress/integration/5-AI-SiteGen-onboarding-flow/4-site-logo.cy.js
Labels: Code Review

#507 Fixed missing ecommerce steps
  src/OnboardingSPA/components/StateHandlers/Flow/index.js
Labels: Code Review

#510 Fix Logo Lag
  src/OnboardingSPA/components/NewfoldInterfaceSkeleton/SiteGen/index.js
Labels: Code Review

#512 Removed error state from fork and welcome step
  src/OnboardingSPA/components/NewfoldInterfaceSkeleton/SiteGen/index.js
  src/OnboardingSPA/steps/SiteGen/Welcome/index.js
  src/OnboardingSPA/steps/TheFork/index.js
Labels: Code Review

#514 fix style lint for logo container background changes
  src/OnboardingSPA/components/ImageUploader/components/ImageUploaderWithText/index.js
  src/OnboardingSPA/components/ImageUploader/components/ImageUploaderWithText/stylesheet.scss
Labels: Ready to merge

#517 Install Plugins Extended
  includes/Services/PluginService.php
Labels: Ready to merge

#522 Cypress tests for Events in site-features page
  tests/cypress/integration/2-general-onboarding-flow/basic-info.cy.js
  tests/cypress/integration/2-general-onboarding-flow/get-started-experience.cy.js
  tests/cypress/integration/2-general-onboarding-flow/site-features.cy.js
  tests/cypress/integration/2-general-onboarding-flow/sitetype-primary.cy.js
  tests/cypress/integration/2-general-onboarding-flow/sitetype-secondary.cy.js
  tests/cypress/integration/2-general-onboarding-flow/top-priority.cy.js
  tests/cypress/integration/3-ecommerce-onboarding-flow/basic-info.cy.js
  tests/cypress/integration/3-ecommerce-onboarding-flow/get-started-experience.cy.js
  tests/cypress/integration/3-ecommerce-onboarding-flow/site-features.cy.js
  tests/cypress/integration/3-ecommerce-onboarding-flow/sitetype-primary.cy.js
  tests/cypress/integration/3-ecommerce-onboarding-flow/sitetype-secondary.cy.js
  tests/cypress/integration/wp-module-support/EventsApi.cy.js
Labels: Ready to merge

#524 Fix PHP warnings
  composer.json
  composer.lock
  includes/Services/PluginService.php
Labels: Code Review

#527 Fix `Priorities`
  includes/Services/PluginService.php
Labels: Ready to merge

#526 Sitegen: Report an event when the error state is triggered
  src/OnboardingSPA/components/StateHandlers/SitegenAi/index.js
  src/OnboardingSPA/utils/analytics/hiive/constants.js
Labels: Code Review
