Repository newfold-labs/wp-module-onboarding, pull requests merged in 2024-02, with the labels that each got.

#436 UI bug fixes reported
  src/OnboardingSPA/components/LivePreview/SiteGenPreviewSelectableCard/stylesheet.scss
  src/OnboardingSPA/components/Sidebar/components/Customize/DesignFontsPanel/index.js
  src/OnboardingSPA/steps/SiteGen/Editor/Header/center.js
  src/OnboardingSPA/steps/SiteGen/Editor/Header/index.js
  src/OnboardingSPA/steps/SiteGen/Editor/stylesheet.scss
  src/OnboardingSPA/steps/SiteGen/Preview/stylesheet.scss
Labels: Code Review

#428 Fix issue with onboarding in AI branch
  src/OnboardingSPA/components/Button/index.js
  src/OnboardingSPA/components/HeadingWithSubHeading/SiteGen/index.js
  src/OnboardingSPA/components/NewfoldInterfaceSkeleton/SiteBuild/index.js
  src/OnboardingSPA/components/NewfoldInterfaceSkeleton/index.js
Labels: Code Review

#448 Preview step enhancements
  src/OnboardingSPA/components/Header/components/SiteGenHeader/step-navigation.js
  src/OnboardingSPA/components/NewfoldInterfaceSkeleton/SiteGen/index.js
  src/OnboardingSPA/steps/SiteGen/SiteDetails/index.js
Labels: Code Review

#450 Add ellipse to long theme names
  src/OnboardingSPA/components/LivePreview/SiteGenPreviewSelectableCard/index.js
  src/OnboardingSPA/components/LivePreview/SiteGenPreviewSelectableCard/stylesheet.scss
  src/OnboardingSPA/components/Sidebar/components/SitegenEditorPatterns/stylesheet.scss
  src/Scripts/sitegen-theme-marker/sitegen-theme-marker.css
  src/Scripts/sitegen-theme-marker/sitegen-theme-marker.js
Labels: Code Review

#446 Add Tests for SiteDetails step
  tests/cypress/integration/5-AI-SiteGen-onboarding-flow/fork.cy.js
  tests/cypress/integration/5-AI-SiteGen-onboarding-flow/site-details.cy.js
  tests/cypress/integration/5-AI-SiteGen-onboarding-flow/site-logo.cy.js
  tests/cypress/integration/5-AI-SiteGen-onboarding-flow/welcome.cy.js
  tests/cypress/integration/wp-module-support/siteGen.cy.js
Labels: Ready to merge

#452 Fix: Custom colors & fonts in the SiteGen customize sidebar is not preserved
  src/OnboardingSPA/components/Sidebar/components/Customize/DesignColorsPanel/ColorPaletteIcon/index.js
  src/OnboardingSPA/components/Sidebar/components/Customize/DesignColorsPanel/index.js
  src/OnboardingSPA/components/Sidebar/components/Customize/DesignFontsPanel/index.js
Labels: Ready to merge

#445 Site error page
  src/OnboardingSPA/components/ImageUploader/components/ImageUploaderWithText/index.js
  src/OnboardingSPA/components/NewfoldInterfaceSkeleton/SiteGen/index.js
  src/OnboardingSPA/components/SiteGenError/contents.js
  src/OnboardingSPA/components/SiteGenError/index.js
  src/OnboardingSPA/components/SiteGenError/stylesheet.scss
  src/OnboardingSPA/components/StateHandlers/SitegenAi/contents.js
  src/OnboardingSPA/components/StateHandlers/SitegenAi/index.js
  src/OnboardingSPA/steps/SiteGen/Building/index.js
  src/OnboardingSPA/steps/SiteGen/Experience/index.js
  src/OnboardingSPA/steps/SiteGen/Preview/index.js
  src/OnboardingSPA/steps/SiteGen/SiteDetails/index.js
  src/OnboardingSPA/steps/SiteGen/SiteLogo/index.js
  src/OnboardingSPA/steps/SiteGen/SocialMedia/index.js
  src/OnboardingSPA/steps/SiteGen/Welcome/index.js
  src/OnboardingSPA/steps/TheFork/index.js
  src/OnboardingSPA/store/actions.js
  src/OnboardingSPA/store/reducer.js
  src/OnboardingSPA/store/selectors.js
  src/OnboardingSPA/styles/app.scss
  src/OnboardingSPA/utils/api/siteGen.js
  src/constants.js
Labels: QA

#457 Fix duplicate API calls in error state handling
  src/OnboardingSPA/components/NewfoldInterfaceSkeleton/SiteGen/index.js
Labels: Ready to merge

#456 `Facebook` Update
  composer.json
  composer.lock
  package-lock.json
  package.json
Labels: Code Review

#453 Cypress Tests for AI SiteGen Preview Step
  tests/cypress/integration/5-AI-SiteGen-onboarding-flow/preview.cy.js
  tests/cypress/integration/5-AI-SiteGen-onboarding-flow/site-details.cy.js
Labels: Ready to merge

#454 Block Render and Screenshots
  includes/RestApi/BlockRenderController.php
  includes/RestApi/RestApi.php
  src/OnboardingSPA/components/LivePreview/BlockPreview/index.js
  src/OnboardingSPA/steps/SiteGen/Editor/Header/index.js
  src/OnboardingSPA/steps/SiteGen/Editor/index.js
  src/OnboardingSPA/utils/api/blockRender.js
Labels: Code Review

#458 Fix minor homepage flicker
  src/OnboardingSPA/steps/SiteGen/Editor/Header/index.js
  src/OnboardingSPA/steps/SiteGen/Preview/index.js
Labels: Code Review

#461 Fix issue with fonts in SiteGen customize sidebar
  src/OnboardingSPA/components/Sidebar/components/Customize/DesignFontsPanel/index.js
Labels: QA

#464 Preserve Customize Selections in State on SiteGen Editor Page
  src/OnboardingSPA/components/Sidebar/components/Customize/DesignColorsPanel/index.js
  src/OnboardingSPA/components/Sidebar/components/Customize/DesignFontsPanel/index.js
  src/OnboardingSPA/steps/SiteGen/Preview/index.js
Labels: Ready to merge

#477 Checking Lint Issue
  package-lock.json
Labels: Code Review

#462 Save continue dim UI
  package-lock.json
  src/OnboardingSPA/components/NewfoldInterfaceSkeleton/SiteGen/index.js
  src/OnboardingSPA/components/NewfoldInterfaceSkeleton/index.js
  src/OnboardingSPA/components/NewfoldInterfaceSkeleton/style.scss
  src/OnboardingSPA/steps/SiteGen/Editor/Header/center.js
  src/OnboardingSPA/steps/SiteGen/Editor/Header/index.js
  src/OnboardingSPA/store/actions.js
  src/OnboardingSPA/store/reducer.js
  src/OnboardingSPA/store/selectors.js
Labels: Code Review

#463 Bug Fixes
  src/OnboardingSPA/components/CardWithOptions/index.js
  src/OnboardingSPA/components/CardWithOptions/stylesheet.scss
  src/OnboardingSPA/components/Drawer/DrawerPanel/NavPrimary.js
  src/OnboardingSPA/components/LivePreview/SiteGenPreviewSelectableCard/stylesheet.scss
  src/OnboardingSPA/components/Loaders/SiteGenLoader/index.js
  src/OnboardingSPA/components/OptionWithHeadingSubHeading/index.js
  src/OnboardingSPA/components/OptionWithHeadingSubHeading/stylesheet.scss
  src/OnboardingSPA/data/models/Step.js
  src/OnboardingSPA/steps/SiteGen/Building/index.js
  src/OnboardingSPA/steps/SiteGen/Editor/Header/center.js
  src/OnboardingSPA/steps/SiteGen/Experience/contents.js
  src/OnboardingSPA/steps/SiteGen/Experience/index.js
  src/OnboardingSPA/steps/SiteGen/Preview/index.js
  src/OnboardingSPA/steps/SiteGen/Preview/stylesheet.scss
  src/OnboardingSPA/steps/SiteGen/SiteLogo/index.js
  src/OnboardingSPA/steps/SiteGen/SocialMedia/index.js
  src/OnboardingSPA/steps/TheFork/step.js
  src/OnboardingSPA/styles/app.scss
Labels: Code Review

#471 More Minor Changes
  src/OnboardingSPA/steps/SiteGen/Building/index.js
  src/OnboardingSPA/steps/SiteGen/Editor/index.js
  src/OnboardingSPA/steps/SiteGen/Experience/index.js
  src/OnboardingSPA/steps/SiteGen/Preview/index.js
  src/OnboardingSPA/steps/SiteGen/SiteDetails/index.js
  src/OnboardingSPA/steps/SiteGen/SiteDetails/stylesheet.scss
  src/OnboardingSPA/steps/SiteGen/SiteLogo/index.js
  src/OnboardingSPA/steps/SiteGen/SocialMedia/index.js
  src/OnboardingSPA/steps/SiteGen/Welcome/contents.js
  src/OnboardingSPA/steps/TheFork/contents.js
  src/OnboardingSPA/steps/TheFork/index.js
  src/OnboardingSPA/steps/TheFork/stylesheet.scss
Labels: Code Review

#467 Press2 1679 bugfix regenerate version naming tab hover
  src/OnboardingSPA/components/TabPanelHover/index.js
  src/OnboardingSPA/steps/SiteGen/Editor/Header/index.js
Labels: Code Review

#468 delete homepage data when prompt changes
  src/OnboardingSPA/steps/SiteGen/SiteDetails/index.js
Labels: Code Review

#474 Replace menu items in previews with those from the sitemap
  includes/RestApi/RestApiFilter.php
Labels: Code Review

#475 Add Site Title and Tagline
  includes/WP_Admin.php
  src/OnboardingSPA/components/NewfoldInterfaceSkeleton/SiteGen/index.js
Labels: Code Review

#483 Fix issue with undefined function data_get()
  composer.json
  composer.lock
  includes/LoginRedirect.php
Labels: bug

#485 Reappear the disappeared Exit button.
  src/OnboardingSPA/components/Header/components/SiteBuildHeader/index.js
Labels: Code Review

#481 Logo background contrast bw images
  src/OnboardingSPA/components/ImageUploader/components/ImageUploaderWithText/index.js
  src/OnboardingSPA/components/ImageUploader/components/ImageUploaderWithText/stylesheet.scss
Labels: Code Review

#484 Update to use Node 16 instead of 14
  .github/workflows/prepare-release.yml
  .nvmrc
  package-lock.json
Labels: dependencies, QA

#493 Sitegen: Fix Site Logo Data
  src/OnboardingSPA/components/ImageUploader/components/ImageUploaderWithText/index.js
  src/OnboardingSPA/steps/SiteGen/SiteLogo/index.js
Labels: Ready to merge

#492 Sitegen: Analytics
  src/OnboardingSPA/chapters/siteGen/core.js
  src/OnboardingSPA/chapters/siteGen/design.js
  src/OnboardingSPA/chapters/siteGen/features.js
  src/OnboardingSPA/chapters/sitegen.js
  src/OnboardingSPA/components/LivePreview/SiteGenPreviewSelectableCard/index.js
  src/OnboardingSPA/components/NewfoldInterfaceSkeleton/SiteGen/index.js
  src/OnboardingSPA/components/Sidebar/components/Customize/DesignColorsPanel/ColorPaletteIcon/index.js
  src/OnboardingSPA/components/Sidebar/components/Customize/DesignColorsPanel/index.js
  src/OnboardingSPA/components/Sidebar/components/Customize/DesignFontsPanel/index.js
  src/OnboardingSPA/components/Sidebar/components/SitegenEditorPatterns/Sidebar.js
  src/OnboardingSPA/components/StartOptions/index.js
  src/OnboardingSPA/components/TextInput/TextInputSiteGen/index.js
  src/OnboardingSPA/data/flows/sitegen.js
  src/OnboardingSPA/steps/SiteGen/Editor/Header/index.js
  src/OnboardingSPA/steps/SiteGen/Experience/index.js
  src/OnboardingSPA/steps/SiteGen/Preview/index.js
  src/OnboardingSPA/steps/SiteGen/SiteDetails/index.js
  src/OnboardingSPA/steps/SiteGen/SiteLogo/index.js
  src/OnboardingSPA/steps/SiteGen/SocialMedia/index.js
  src/OnboardingSPA/steps/TheFork/index.js
  src/OnboardingSPA/steps/TheFork/stylesheet.scss
  src/OnboardingSPA/styles/_branding.scss
  src/OnboardingSPA/utils/analytics/hiive/constants.js
  src/constants.js
Labels: Ready to merge

#491 Remove overlapping of Exit to WordPress button on smaller screens
  src/OnboardingSPA/components/Header/stylesheet.scss
Labels: Ready to merge

#489 Update SiteGen Cypress Tests
  package-lock.json
  tests/cypress/integration/5-AI-SiteGen-onboarding-flow/1-fork.cy.js
  tests/cypress/integration/5-AI-SiteGen-onboarding-flow/2-welcome.cy.js
  tests/cypress/integration/5-AI-SiteGen-onboarding-flow/3-site-details.cy.js
  tests/cypress/integration/5-AI-SiteGen-onboarding-flow/4-site-logo.cy.js
  tests/cypress/integration/5-AI-SiteGen-onboarding-flow/5-experience.cy.js
  tests/cypress/integration/5-AI-SiteGen-onboarding-flow/6-preview.cy.js
  tests/cypress/integration/wp-module-support/siteGen.cy.js
  tests/cypress/integration/wp-module-support/socialMedia.cy.js
Labels: Ready to merge

#490 updated fork: redirect to old flow if ai sitegen is false
  src/OnboardingSPA/steps/TheFork/index.js
  tests/cypress/integration/2-general-onboarding-flow/get-started-welcome.cy.js
  tests/cypress/integration/3-ecommerce-onboarding-flow/get-started-welcome.cy.js
Labels: Code Review

#466 Disable the back button in the normal flow when a user lands from the error state.
  src/OnboardingSPA/components/Header/components/SiteBuildHeader/step-navigation.js
  src/OnboardingSPA/components/SiteGenError/index.js
  src/OnboardingSPA/components/StartOptions/index.js
  src/OnboardingSPA/store/actions.js
  src/OnboardingSPA/store/reducer.js
Labels: Code Review
