Repository newfold-labs/wp-module-onboarding, pull requests merged in 2024-01, with the labels that each got.

#394 Fix Dynamic BG
  src/OnboardingSPA/components/NewfoldInterfaceSkeleton/index.js
  src/OnboardingSPA/components/NewfoldInterfaceSkeleton/style.scss
  src/OnboardingSPA/static/images/sitegen/ai_bg.png
  src/OnboardingSPA/static/images/sitegen/ai_bg_low.png
  src/OnboardingSPA/styles/_branding.scss
  src/OnboardingSPA/styles/_icons.scss
Labels: Ready to merge

#397 Input Score Analyser
  src/OnboardingSPA/components/TextInput/TextInputSiteGen/index.js
  src/OnboardingSPA/steps/SiteGen/SiteDetails/index.js
Labels: Ready to merge

#402 Re-enabled exits and enhance the logic for the coming soon.
  includes/Application.php
  includes/RestApi/FlowController.php
  includes/RestApi/SettingsController.php
  includes/Services/StatusService.php
  src/OnboardingSPA/components/Drawer/DrawerPanel/NavPrimary.js
  src/OnboardingSPA/components/ExitToWordPress/index.js
  src/OnboardingSPA/components/Header/index.js
  src/OnboardingSPA/components/Loaders/Chapter/Interstitial/index.js
  src/OnboardingSPA/steps/Complete/index.js
  src/OnboardingSPA/utils/api/comingSoon.js
Labels: Ready to merge

#407 Fix fonts for orchid shades and correct typography step issues
  src/OnboardingSPA/components/App/index.js
  src/OnboardingSPA/components/Drawer/DrawerPanel/DesignFonts.js
Labels: Ready to merge

#404 Demo/sitegen mvp fixes 2
  includes/RestApi/SiteGenController.php
  src/OnboardingSPA/components/Sidebar/components/Customize/DesignColorsPanel/ColorPaletteIcon/index.js
  src/OnboardingSPA/components/Sidebar/components/Customize/DesignColorsPanel/ColorPaletteIcon/stylesheet.scss
  src/OnboardingSPA/components/Sidebar/components/Customize/DesignColorsPanel/CustomColorPalette/index.js
  src/OnboardingSPA/components/Sidebar/components/Customize/DesignColorsPanel/CustomColorPalette/stylesheet.scss
  src/OnboardingSPA/components/Sidebar/components/Customize/DesignColorsPanel/index.js
  src/OnboardingSPA/components/Sidebar/components/Customize/DesignColorsPanel/stylesheet.scss
  src/OnboardingSPA/components/Sidebar/components/Customize/DesignFontsPanel/index.js
  src/OnboardingSPA/components/Sidebar/components/Customize/DesignFontsPanel/stylesheet.scss
  src/OnboardingSPA/steps/SiteGen/Editor/Sidebar/Customize/index.js
  src/OnboardingSPA/steps/SiteGen/Editor/index.js
  src/OnboardingSPA/styles/_branding.scss
Labels: WIP

#410 PRESS2-1489 Add Cypress Tests for site-logo step
  tests/cypress/integration/5-AI-SiteGen-onboarding-flow/site-logo.cy.js
  tests/cypress/integration/5-AI-SiteGen-onboarding-flow/welcome.cy.js
  tests/cypress/integration/wp-module-support/siteGen.cy.js
Labels: Ready to merge

#380 Api integration preview home page
  includes/RestApi/SiteGenController.php
  src/OnboardingSPA/components/Button/ButtonDark/stylesheet.scss
  src/OnboardingSPA/components/Button/index.js
  src/OnboardingSPA/components/Footer/components/SiteGenFooter/index.js
  src/OnboardingSPA/components/Header/components/SiteGenHeader/index.js
  src/OnboardingSPA/components/Header/index.js
  src/OnboardingSPA/components/Header/stylesheet.scss
  src/OnboardingSPA/components/LivePreview/BlockPreview/stylesheet.scss
  src/OnboardingSPA/components/LivePreview/BlockPreviewSiteGen/auto.js
  src/OnboardingSPA/components/LivePreview/BlockPreviewSiteGen/index.js
  src/OnboardingSPA/components/LivePreview/SelectableCard/stylesheet.scss
  src/OnboardingSPA/components/LivePreview/SiteGenPreviewSelectableCard/index.js
  src/OnboardingSPA/components/LivePreview/SiteGenPreviewSelectableCard/stylesheet.scss
  src/OnboardingSPA/components/LivePreview/index.js
  src/OnboardingSPA/components/LivePreview/stylesheet.scss
  src/OnboardingSPA/components/Loaders/SiteGenLoader/index.js
  src/OnboardingSPA/components/NewfoldInterfaceSkeleton/SiteGen/index.js
  src/OnboardingSPA/components/NewfoldInterfaceSkeleton/style.scss
  src/OnboardingSPA/static/icons/equalizer.svg
  src/OnboardingSPA/static/icons/sitegen/heart-filled.svg
  src/OnboardingSPA/static/icons/sitegen/heart-stroked.svg
  src/OnboardingSPA/steps/SiteGen/Editor/Header/TextInput/index.js
  src/OnboardingSPA/steps/SiteGen/Editor/Header/step-navigation-center.js
  src/OnboardingSPA/steps/SiteGen/Editor/Header/step-navigation-left.js
  src/OnboardingSPA/steps/SiteGen/Editor/Header/step-navigation-right.js
  src/OnboardingSPA/steps/SiteGen/Editor/stylesheet.scss
  src/OnboardingSPA/steps/SiteGen/Preview/contents.js
  src/OnboardingSPA/steps/SiteGen/Preview/heartAnimation.js
  src/OnboardingSPA/steps/SiteGen/Preview/index.js
  src/OnboardingSPA/steps/SiteGen/Preview/pattern.js
  src/OnboardingSPA/steps/SiteGen/Preview/regeneratingCard.js
  src/OnboardingSPA/steps/SiteGen/Preview/stylesheet.scss
  src/OnboardingSPA/store/actions.js
  src/OnboardingSPA/store/reducer.js
  src/OnboardingSPA/store/selectors.js
  src/OnboardingSPA/styles/_branding.scss
  src/OnboardingSPA/styles/_interface.scss
  src/OnboardingSPA/styles/app.scss
  src/OnboardingSPA/utils/api/siteGen.js
  src/constants.js
Labels: Code Review

#382 Adding simple customer promt screen
  includes/RestApi/SiteGenController.php
  src/OnboardingSPA/components/TextInput/TextAreaSiteGenDetails/index.js
  src/OnboardingSPA/components/TextInput/TextAreaSiteGenDetails/stylesheet.scss
  src/OnboardingSPA/components/TextInput/TextInputSiteGenDetails/index.js
  src/OnboardingSPA/components/TextInput/TextInputSiteGenDetails/stylesheet.scss
  src/OnboardingSPA/steps/SiteGen/SiteDetails/contents.js
  src/OnboardingSPA/steps/SiteGen/SiteDetails/index.js
  src/OnboardingSPA/steps/SiteGen/SiteDetails/stylesheet.scss
  src/OnboardingSPA/steps/SiteGen/SiteDetails/walkthrough/index.js
  src/OnboardingSPA/styles/app.scss
  src/OnboardingSPA/utils/api/siteGen.js
Labels: Code Review

#413 Activate WooCommerce by preview step
  includes/Services/PluginService.php
Labels: Code Review

#415 Add homepages to Wonder Blocks templates
  includes/WP_Admin.php
Labels: Code Review

#414 Fix minor visual bugs
  src/OnboardingSPA/components/AdminBar/stylesheet.scss
  src/OnboardingSPA/components/Button/NextButtonSiteGen/index.js
  src/OnboardingSPA/components/Button/NextButtonSiteGen/stylesheet.scss
  src/OnboardingSPA/components/Header/components/SiteGenHeader/index.js
  src/OnboardingSPA/components/ImageUploader/components/ImageUploaderWithText/stylesheet.scss
  src/OnboardingSPA/components/ProgressBar/stylesheet.scss
  src/OnboardingSPA/components/StartOptions/stylesheet.scss
  src/OnboardingSPA/components/TextInput/TextInputSiteGen/index.js
  src/OnboardingSPA/components/TextInput/TextInputSiteGen/stylesheet.scss
  src/OnboardingSPA/steps/SiteGen/SiteDetails/index.js
  src/OnboardingSPA/steps/SiteGen/SiteDetails/stylesheet.scss
  src/OnboardingSPA/steps/SiteGen/SiteLogo/stylesheet.scss
  src/OnboardingSPA/steps/SiteGen/Welcome/contents.js
  src/OnboardingSPA/steps/SiteGen/Welcome/index.js
  src/OnboardingSPA/steps/SiteGen/Welcome/stylesheet.scss
Labels: Code Review

#416 Fix Minor Bugs 2
  src/OnboardingSPA/components/CardWithOptions/stylesheet.scss
  src/OnboardingSPA/components/Footer/stylesheet.scss
  src/OnboardingSPA/components/Heading/AIHeading/stylesheet.scss
  src/OnboardingSPA/steps/SiteGen/SiteLogo/step.js
  src/OnboardingSPA/steps/SiteGen/SocialMedia/contents.js
  src/OnboardingSPA/steps/SiteGen/SocialMedia/stylesheet.scss
  src/OnboardingSPA/steps/TheFork/contents.js
  tests/cypress/integration/5-AI-SiteGen-onboarding-flow/site-logo.cy.js
Labels: Code Review

#412 AI Sitegen Capability Check
  src/OnboardingSPA/components/ImageUploader/components/ImageUploaderWithText/stylesheet.scss
  src/OnboardingSPA/components/StartOptions/index.js
  src/OnboardingSPA/steps/TheFork/contents.js
Labels: Code Review

#421 Remove Detailed Prompt View
  src/OnboardingSPA/steps/SiteGen/SiteDetails/index.js
Labels: Code Review

#419 Update Tests to run across all Brand Plugins
  .github/workflows/brand-plugin-test.yml
  tests/cypress/integration/1-Initial-steps/branding.cy.js
  tests/cypress/integration/1-Initial-steps/whats-next.cy.js
  tests/cypress/integration/2-general-onboarding-flow/basic-info.cy.js
  tests/cypress/integration/2-general-onboarding-flow/exit-to-wordpress.cy.js
  tests/cypress/integration/2-general-onboarding-flow/get-started-experience.cy.js
  tests/cypress/integration/2-general-onboarding-flow/get-started-welcome.cy.js
  tests/cypress/integration/2-general-onboarding-flow/site-features.cy.js
  tests/cypress/integration/2-general-onboarding-flow/sitetype-primary.cy.js
  tests/cypress/integration/2-general-onboarding-flow/sitetype-secondary.cy.js
  tests/cypress/integration/3-ecommerce-onboarding-flow/address.cy.js
  tests/cypress/integration/3-ecommerce-onboarding-flow/basic-info.cy.js
  tests/cypress/integration/3-ecommerce-onboarding-flow/exit-to-wordpress.cy.js
  tests/cypress/integration/3-ecommerce-onboarding-flow/get-started-experience.cy.js
  tests/cypress/integration/3-ecommerce-onboarding-flow/get-started-welcome.cy.js
  tests/cypress/integration/3-ecommerce-onboarding-flow/products.cy.js
  tests/cypress/integration/3-ecommerce-onboarding-flow/site-features.cy.js
  tests/cypress/integration/3-ecommerce-onboarding-flow/sitetype-primary.cy.js
  tests/cypress/integration/3-ecommerce-onboarding-flow/sitetype-secondary.cy.js
  tests/cypress/integration/4-design-steps/colors-step.cy.js
  tests/cypress/integration/4-design-steps/header-menu.cy.js
  tests/cypress/integration/4-design-steps/homepage-styles.cy.js
  tests/cypress/integration/4-design-steps/site-pages.cy.js
  tests/cypress/integration/4-design-steps/theme-styles-menu.cy.js
  tests/cypress/integration/4-design-steps/theme-styles-preview.cy.js
  tests/cypress/integration/4-design-steps/typography-step.cy.js
  tests/cypress/integration/sidebar.cy.js
  tests/cypress/integration/wp-module-support/drawer.cy.js
  tests/cypress/integration/wp-module-support/pluginID.cy.js
  tests/cypress/integration/wp-module-support/sidebar.cy.js
  tests/cypress/integration/wp-module-support/socialMedia.cy.js
Labels: Ready to merge

#426 More Fixes...
  src/OnboardingSPA/components/Footer/components/SiteGenFooter/index.js
  src/OnboardingSPA/components/Loaders/SiteGenLoader/stylesheet.scss
  src/OnboardingSPA/components/Loaders/Spinner/stylesheet.scss
  src/OnboardingSPA/components/TextInput/TextInputSiteGen/stylesheet.scss
  src/OnboardingSPA/steps/SiteGen/Building/stylesheet.scss
  src/OnboardingSPA/steps/SiteGen/Editor/index.js
  src/OnboardingSPA/steps/SiteGen/Experience/index.js
  src/OnboardingSPA/steps/SiteGen/Preview/contents.js
  src/OnboardingSPA/steps/SiteGen/Preview/index.js
  src/OnboardingSPA/steps/SiteGen/Preview/regeneratingCard.js
  src/OnboardingSPA/steps/SiteGen/Preview/stylesheet.scss
  src/OnboardingSPA/steps/SiteGen/SiteDetails/index.js
  src/OnboardingSPA/steps/SiteGen/SiteDetails/walkthrough/index.js
  src/OnboardingSPA/steps/SiteGen/SiteLogo/index.js
  src/OnboardingSPA/steps/SiteGen/SocialMedia/stylesheet.scss
  src/OnboardingSPA/steps/SiteGen/Welcome/index.js
  src/OnboardingSPA/steps/TheFork/index.js
  src/OnboardingSPA/store/actions.js
  src/OnboardingSPA/store/reducer.js
  src/OnboardingSPA/store/selectors.js
Labels: Code Review

#425 Sitegen: Code Refactor and Post-Integration Fixes
  composer.json
  composer.lock
  includes/RestApi/SiteGenController.php
  includes/WP_Admin.php
  package-lock.json
  package.json
  src/OnboardingSPA/chapters/sitegen.js
  src/OnboardingSPA/components/Footer/components/SiteGenFooter/index.js
  src/OnboardingSPA/components/LivePreview/BlockPreview/index.js
  src/OnboardingSPA/components/LivePreview/BlockPreviewSiteGen/auto.js
  src/OnboardingSPA/components/LivePreview/BlockPreviewSiteGen/index.js
  src/OnboardingSPA/components/LivePreview/SiteGenPreviewSelectableCard/index.js
  src/OnboardingSPA/components/LivePreview/index.js
  src/OnboardingSPA/components/Loaders/SiteGenLoader/stylesheet.scss
  src/OnboardingSPA/components/Loaders/Spinner/stylesheet.scss
  src/OnboardingSPA/components/Sidebar/components/Customize/DesignColorsPanel/index.js
  src/OnboardingSPA/components/Sidebar/components/Customize/DesignFontsPanel/index.js
  src/OnboardingSPA/components/Sidebar/components/SitegenEditorPatterns/Sidebar.js
  src/OnboardingSPA/components/TextInput/TextInputSiteGen/stylesheet.scss
  src/OnboardingSPA/data/sitegen/homepages/1.json
  src/OnboardingSPA/data/sitegen/homepages/2.json
  src/OnboardingSPA/data/sitegen/homepages/3.json
  src/OnboardingSPA/data/sitegen/homepages/4.json
  src/OnboardingSPA/data/sitegen/homepages/homepages.js
  src/OnboardingSPA/data/sitegen/sitemeta/siteMeta.js
  src/OnboardingSPA/data/sitegen/sitemeta/siteMeta.json
  src/OnboardingSPA/steps/SiteGen/Building/stylesheet.scss
  src/OnboardingSPA/steps/SiteGen/Editor/Header/TextInput/index.js
  src/OnboardingSPA/steps/SiteGen/Editor/Header/center.js
  src/OnboardingSPA/steps/SiteGen/Editor/Header/index.js
  src/OnboardingSPA/steps/SiteGen/Editor/Header/step-navigation-center.js
  src/OnboardingSPA/steps/SiteGen/Editor/index.js
  src/OnboardingSPA/steps/SiteGen/Experience/index.js
  src/OnboardingSPA/steps/SiteGen/Preview/contents.js
  src/OnboardingSPA/steps/SiteGen/Preview/index.js
  src/OnboardingSPA/steps/SiteGen/Preview/regeneratingCard.js
  src/OnboardingSPA/steps/SiteGen/Preview/stylesheet.scss
  src/OnboardingSPA/steps/SiteGen/SiteDetails/index.js
  src/OnboardingSPA/steps/SiteGen/SiteDetails/walkthrough/index.js
  src/OnboardingSPA/steps/SiteGen/SiteLogo/index.js
  src/OnboardingSPA/steps/SiteGen/SocialMedia/index.js
  src/OnboardingSPA/steps/SiteGen/SocialMedia/stylesheet.scss
  src/OnboardingSPA/steps/SiteGen/Welcome/index.js
  src/OnboardingSPA/steps/TheFork/index.js
  src/OnboardingSPA/store/actions.js
  src/OnboardingSPA/store/reducer.js
  src/OnboardingSPA/store/selectors.js
  src/OnboardingSPA/styles/_branding.scss
  src/OnboardingSPA/utils/api/siteGen.js
  src/Scripts/sitegen-theme-marker/sitegen-theme-marker.js
Labels: Code Review

#427 ui fixes
  src/OnboardingSPA/components/Button/NextButtonSiteGen/index.js
  src/OnboardingSPA/components/Button/NextButtonSiteGen/stylesheet.scss
  src/OnboardingSPA/components/HeadingWithSubHeading/SiteGen/stylesheet.scss
  src/OnboardingSPA/components/ImageUploader/components/ImageUploaderWithText/stylesheet.scss
  src/OnboardingSPA/components/StartOptions/stylesheet.scss
  src/OnboardingSPA/steps/SiteGen/SiteLogo/stylesheet.scss
  src/OnboardingSPA/steps/SiteGen/SocialMedia/stylesheet.scss
  src/OnboardingSPA/styles/_branding.scss
Labels: Code Review

#434 Bump Onboarding to 1.12.1
  bootstrap.php
  build/1.12.1/111.js
  build/1.12.1/128.js
  build/1.12.1/244.js
  build/1.12.1/310.js
  build/1.12.1/33.js
  build/1.12.1/405.js
  build/1.12.1/420.js
  build/1.12.1/449.js
  build/1.12.1/465.js
  build/1.12.1/491.js
  build/1.12.1/537.js
  build/1.12.1/574.js
  build/1.12.1/58.js
  build/1.12.1/657.js
  build/1.12.1/662.js
  build/1.12.1/696.js
  build/1.12.1/704.js
  build/1.12.1/719.js
  build/1.12.1/73.js
  build/1.12.1/76.js
  build/1.12.1/792.js
  build/1.12.1/849.js
  build/1.12.1/856.js
  build/1.12.1/993.js
  build/1.12.1/994.js
  build/1.12.1/images/bluesky.733ebcbf.png
  build/1.12.1/images/content.fb050ea1.png
  build/1.12.1/images/design.cc6a697f.png
  build/1.12.1/images/features.593fb09c.png
  build/1.12.1/images/full-service.7f58f410.png
  build/1.12.1/images/full-service.adb3abd6.png
  build/1.12.1/images/help.19cc7e75.png
  build/1.12.1/images/step-interstitial.00b15f9e.png
  build/1.12.1/images/wp-admin.2908b886.png
  build/1.12.1/images/wp-admin.6c8af0b4.png
  build/1.12.1/images/wp-admin.d8650899.png
  build/1.12.1/onboarding.asset.php
  build/1.12.1/onboarding.css
  build/1.12.1/onboarding.js
  package-lock.json
  package.json
Labels: Ready to merge

#430 Add Tests for Experience & Site Building Step
  tests/cypress/integration/5-AI-SiteGen-onboarding-flow/experience.cy.js
  tests/cypress/integration/wp-module-support/siteGen.cy.js
Labels: Ready to merge

#433 Reset the customized fonts and colors in SiteGen Preview
  src/OnboardingSPA/components/Sidebar/components/Customize/DesignColorsPanel/index.js
  src/OnboardingSPA/components/Sidebar/components/Customize/DesignFontsPanel/index.js
  src/OnboardingSPA/components/Sidebar/components/Customize/Sidebar.js
  src/OnboardingSPA/steps/SiteGen/Editor/Sidebar/Customize/index.js
Labels: QA

#438 Separate out header, content and footer for homepages
  composer.json
  composer.lock
  package-lock.json
  src/OnboardingSPA/components/Sidebar/components/SitegenEditorPatterns/Sidebar.js
  src/OnboardingSPA/steps/SiteGen/Editor/index.js
  src/OnboardingSPA/steps/SiteGen/Preview/index.js
Labels: Code Review

#435 Fix hirepro
  src/OnboardingSPA/components/StartOptions/index.js
  src/OnboardingSPA/steps/TheFork/contents.js
Labels: Code Review

#444 Fix lint in `enhance/ai-onboarding` branch
  src/OnboardingSPA/components/Button/NextButtonSiteGen/index.js
  src/OnboardingSPA/components/Header/index.js
  src/OnboardingSPA/components/Sidebar/components/Customize/DesignColorsPanel/index.js
  src/Scripts/sitegen-theme-marker/sitegen-theme-marker.js
Labels: Code Review
