Repository newfold-labs/wp-module-onboarding, pull requests merged in 2024-06, with the labels that each got.

#541 Add Defensive Checks Just in case
  src/OnboardingSPA/components/Drawer/DrawerPanel/DesignHeaderMenu.js
Labels: Ready to merge

#571 Improve Error Handling for `FacebookConnectButton`
  src/OnboardingSPA/steps/SiteGen/SocialMedia/index.js
Labels: Code Review

#572 Initialize plugins in the fork step
  src/OnboardingSPA/steps/TheFork/index.js
Labels: Code Review

#573 Move `configure_activation_transient` to page loads only
  includes/Application.php
Labels: Code Review

#575 Fix Multilingual Reporting of Event Values
  src/OnboardingSPA/components/NewfoldInterfaceSkeleton/SiteBuild/index.js
  src/OnboardingSPA/data/models/Step.js
  src/OnboardingSPA/steps/BasicInfo/step.js
  src/OnboardingSPA/steps/Complete/step.js
  src/OnboardingSPA/steps/DesignColors/step.js
  src/OnboardingSPA/steps/DesignFonts/step.js
  src/OnboardingSPA/steps/DesignHeaderMenu/step.js
  src/OnboardingSPA/steps/DesignHomepageMenu/step.js
  src/OnboardingSPA/steps/DesignThemeStyles/Menu/step.js
  src/OnboardingSPA/steps/DesignThemeStyles/Preview/step.js
  src/OnboardingSPA/steps/Ecommerce/StepAddress/step.js
  src/OnboardingSPA/steps/Ecommerce/StepProducts/step.js
  src/OnboardingSPA/steps/Ecommerce/StepTax/step.js
  src/OnboardingSPA/steps/GetStarted/GetStartedExperience/step.js
  src/OnboardingSPA/steps/GetStarted/SiteTypeSetup/PrimarySite/step.js
  src/OnboardingSPA/steps/GetStarted/SiteTypeSetup/SecondarySite/step.js
  src/OnboardingSPA/steps/GetStarted/Welcome/step.js
  src/OnboardingSPA/steps/SiteFeatures/step.js
  src/OnboardingSPA/steps/SiteGen/Editor/step.js
  src/OnboardingSPA/steps/SiteGen/Experience/step.js
  src/OnboardingSPA/steps/SiteGen/Migration/step.js
  src/OnboardingSPA/steps/SiteGen/Preview/step.js
  src/OnboardingSPA/steps/SiteGen/SiteDetails/step.js
  src/OnboardingSPA/steps/SiteGen/SiteLogo/step.js
  src/OnboardingSPA/steps/SiteGen/SocialMedia/step.js
  src/OnboardingSPA/steps/SiteGen/Welcome/step.js
  src/OnboardingSPA/steps/SitePages/index.js
  src/OnboardingSPA/steps/SitePages/step.js
  src/OnboardingSPA/steps/TheFork/step.js
  src/OnboardingSPA/steps/TopPriority/index.js
  src/OnboardingSPA/steps/TopPriority/step.js
  src/OnboardingSPA/steps/WhatNext/step.js
Labels: Ready to merge

#576 Fix Onboarding Site Details Error Screen
  src/OnboardingSPA/components/NewfoldInterfaceSkeleton/SiteGen/index.js
  src/constants.js
Labels: Ready to merge

#578 Remove SiteGen Welcome Step
  src/OnboardingSPA/chapters/sitegen.js
  src/OnboardingSPA/data/flows/sitegen.js
  tests/cypress/integration/5-AI-SiteGen-onboarding-flow/1-fork.cy.js
  tests/cypress/integration/5-AI-SiteGen-onboarding-flow/2-welcome.cy.js
  tests/cypress/integration/5-AI-SiteGen-onboarding-flow/3-site-details.cy.js
  tests/cypress/integration/5-AI-SiteGen-onboarding-flow/4-site-logo.cy.js
  tests/cypress/integration/5-AI-SiteGen-onboarding-flow/5-experience.cy.js
  tests/cypress/integration/5-AI-SiteGen-onboarding-flow/6-preview.cy.js
Labels: Ready to merge

#580 Press0 1453 dark mode on preview step
  src/OnboardingSPA/chapters/sitegen.js
  src/OnboardingSPA/data/flows/sitegen.js
  tests/cypress/integration/5-AI-SiteGen-onboarding-flow/1-fork.cy.js
  tests/cypress/integration/5-AI-SiteGen-onboarding-flow/2-welcome.cy.js
  tests/cypress/integration/5-AI-SiteGen-onboarding-flow/3-site-details.cy.js
  tests/cypress/integration/5-AI-SiteGen-onboarding-flow/4-site-logo.cy.js
  tests/cypress/integration/5-AI-SiteGen-onboarding-flow/5-experience.cy.js
  tests/cypress/integration/5-AI-SiteGen-onboarding-flow/6-preview.cy.js
Labels: WIP

#579 Remove Chevron Experience Step
  src/OnboardingSPA/components/OptionWithHeadingSubHeading/index.js
  src/OnboardingSPA/components/OptionWithHeadingSubHeading/stylesheet.scss
Labels: Ready to merge

#586 Fix issue with custom fonts preview
  src/OnboardingSPA/components/Sidebar/components/Customize/DesignFontsPanel/index.js
Labels: QA

#577 migration_initiation event from sitebuild
  src/OnboardingSPA/components/Layouts/Base.js
  src/OnboardingSPA/components/NewfoldInterfaceSkeleton/SiteBuild/index.js
  src/OnboardingSPA/components/NewfoldInterfaceSkeleton/SiteGen/index.js
  src/OnboardingSPA/steps/GetStarted/Welcome/index.js
  src/OnboardingSPA/steps/SiteGen/Migration/index.js
  src/OnboardingSPA/steps/TheFork/index.js
  src/OnboardingSPA/store/actions.js
  src/OnboardingSPA/store/reducer.js
  src/OnboardingSPA/store/selectors.js
Labels: Ready to merge

#584 Integrate Sentry
  package-lock.json
  package.json
  src/onboarding.js
Labels: Ready to merge

#585 Add Min Char Threshold Site Details
  src/OnboardingSPA/steps/SiteGen/SiteDetails/index.js
Labels: Ready to merge

#587 Remove `flow` param for Events API requests
  .github/workflows/lint-check-php.yml
  src/OnboardingSPA/utils/api/common.js
  src/onboarding.js
  tests/cypress/integration/wp-module-support/EventsApi.cy.js
Labels: Ready to merge

#588 Fix Chevron in Save and Continue
  src/OnboardingSPA/steps/SiteGen/Editor/Header/index.js
  src/OnboardingSPA/steps/SiteGen/Editor/Header/stylesheet.scss
Labels: Ready to merge

#590 Add identifiers when the error state is triggered
  src/OnboardingSPA/components/NewfoldInterfaceSkeleton/SiteGen/index.js
  src/OnboardingSPA/components/StateHandlers/SiteGen/index.js
  src/OnboardingSPA/steps/SiteGen/Migration/index.js
  src/OnboardingSPA/steps/SiteGen/Preview/index.js
  src/OnboardingSPA/steps/SiteGen/SiteLogo/index.js
  src/OnboardingSPA/steps/SiteGen/SocialMedia/index.js
  src/OnboardingSPA/utils/analytics/hiive/constants.js
Labels: Ready to merge

#589 bug/previews other than favorites in favorit tab
  src/OnboardingSPA/components/Sidebar/components/SitegenEditorPatterns/Sidebar.js
Labels: QA
