Repository newfold-labs/wp-module-onboarding, pull requests merged in 2024-05, with the labels that each got.

#545 fixing failures and enabling skipped tests
  tests/cypress/fixtures/homepage-regenerate.json
  tests/cypress/fixtures/homepages.json
  tests/cypress/integration/5-AI-SiteGen-onboarding-flow/3-site-details.cy.js
  tests/cypress/integration/5-AI-SiteGen-onboarding-flow/4-site-logo.cy.js
  tests/cypress/integration/5-AI-SiteGen-onboarding-flow/5-experience.cy.js
  tests/cypress/integration/5-AI-SiteGen-onboarding-flow/6-preview.cy.js
  tests/cypress/integration/5-AI-SiteGen-onboarding-flow/7-editor.cy.js
  tests/cypress/integration/wp-module-support/MockApi.cy.js
Labels: Code Review

#538 changed url to wpsiteurl in mini-preview instead of dummy domain
  src/OnboardingSPA/components/MiniPreview/contents.js
  src/OnboardingSPA/components/MiniPreview/index.js
Labels: Ready to merge

#548 Apply Fork A/B Test Winner
  src/OnboardingSPA/components/StartOptions/contents.js
  src/OnboardingSPA/components/StartOptions/index.js
  src/OnboardingSPA/components/StartOptions/stylesheet.scss
  src/OnboardingSPA/steps/TheFork/contents.js
  src/OnboardingSPA/steps/TheFork/index.js
  src/OnboardingSPA/utils/analytics/hiive/constants.js
  src/onboarding.js
Labels: Ready to merge

#549 Fix Tracking Bugs in AI WonderStart Flow
  src/OnboardingSPA/steps/SiteGen/Editor/Header/index.js
  src/OnboardingSPA/steps/SiteGen/SiteLogo/index.js
Labels: Ready to merge

#551 Switch to Fresh Installation check before activating Wonder Theme
  composer.json
  composer.lock
  includes/LoginRedirect.php
  src/OnboardingSPA/components/Button/NavCardButton/index.js
  src/OnboardingSPA/components/Header/components/SiteBuildHeader/step-navigation.js
  src/OnboardingSPA/components/StateHandlers/Design/contents.js
  src/OnboardingSPA/components/StateHandlers/Design/index.js
  src/OnboardingSPA/store/actions.js
  src/OnboardingSPA/store/selectors.js
Labels: Ready to merge

#543 Migrate screen via the site import link
  composer.json
  composer.lock
  src/OnboardingSPA/components/ErrorState/Step/SiteGen/contents.js
  src/OnboardingSPA/components/ErrorState/Step/SiteGen/index.js
  src/OnboardingSPA/components/ErrorState/Step/SiteGen/stylesheet.scss
  src/OnboardingSPA/components/Header/components/SiteGenHeader/index.js
  src/OnboardingSPA/components/Header/components/SiteGenHeader/step-navigation.js
  src/OnboardingSPA/components/HeadingWithSubHeading/SiteGen/stylesheet.scss
  src/OnboardingSPA/components/NewfoldInterfaceSkeleton/SiteBuild/index.js
  src/OnboardingSPA/components/StateHandlers/SiteGen/index.js
  src/OnboardingSPA/data/flows/default.js
  src/OnboardingSPA/data/flows/ecommerce.js
  src/OnboardingSPA/data/flows/sitegen.js
  src/OnboardingSPA/data/flows/utils.js
  src/OnboardingSPA/steps/GetStarted/Welcome/index.js
  src/OnboardingSPA/steps/SiteGen/Migration/contents.js
  src/OnboardingSPA/steps/SiteGen/Migration/index.js
  src/OnboardingSPA/steps/SiteGen/Migration/step.js
  src/OnboardingSPA/steps/SiteGen/Migration/stylesheet.scss
  src/OnboardingSPA/steps/TheFork/index.js
  src/OnboardingSPA/steps/TheFork/stylesheet.scss
  src/OnboardingSPA/store/selectors.js
  src/OnboardingSPA/styles/app.scss
  src/OnboardingSPA/utils/analytics/hiive/constants.js
  src/OnboardingSPA/utils/api/common.js
  src/OnboardingSPA/utils/api/siteGen.js
  src/constants.js
Labels: QA

#561 PRESS0-1329 | Cypress tests for Migration initiation screen
  tests/cypress/fixtures/migrate-connect.json
  tests/cypress/integration/5-AI-SiteGen-onboarding-flow/1-fork.cy.js
  tests/cypress/integration/wp-module-support/MockApi.cy.js
Labels: Ready to merge

#559 Press0 1173 placeholder prompt input
  build/2.3.0/390.js
  build/2.3.0/onboarding.asset.php
  build/2.3.0/onboarding.css
  languages/wp-module-onboarding-pt_BR-nfd-onboarding.json
  languages/wp-module-onboarding-pt_BR.mo
  languages/wp-module-onboarding-pt_BR.po
  languages/wp-module-onboarding.pot
  src/OnboardingSPA/components/TextInput/TextInputSiteGen/stylesheet.scss
  src/OnboardingSPA/steps/SiteGen/SiteDetails/contents.js
  tests/cypress/integration/5-AI-SiteGen-onboarding-flow/3-site-details.cy.js
Labels: QA

#562 Limit AI Retries
  src/OnboardingSPA/components/ErrorState/Step/SiteGen/index.js
  src/OnboardingSPA/components/NewfoldInterfaceSkeleton/SiteGen/index.js
  src/OnboardingSPA/store/reducer.js
  src/OnboardingSPA/store/selectors.js
Labels: Ready to merge

#560 Remove Char Limits on Site Details Step
  src/OnboardingSPA/components/TextInput/TextInputSiteGen/contents.js
  src/OnboardingSPA/components/TextInput/TextInputSiteGen/index.js
  src/OnboardingSPA/components/TextInput/TextInputSiteGen/stylesheet.scss
  src/OnboardingSPA/steps/SiteGen/SiteDetails/index.js
  tests/cypress/integration/5-AI-SiteGen-onboarding-flow/3-site-details.cy.js
Labels: QA

#565 Press0 1328 default to light mode
  src/OnboardingSPA/components/ThemeContextProvider/index.js
  tests/cypress/integration/wp-module-support/siteGen.cy.js
Labels: Ready to merge
