Repository newfold-labs/wp-module-onboarding, pull requests merged in 2024-04, with the labels that each got.

#521 Character count in Site Details
  src/OnboardingSPA/components/TextInput/TextInputSiteGen/contents.js
  src/OnboardingSPA/components/TextInput/TextInputSiteGen/index.js
  src/OnboardingSPA/components/TextInput/TextInputSiteGen/stylesheet.scss
Labels: Ready to merge

#523 Enhancement: Verify 'Yith Wonder' Theme Activation in Preview & Editor Step
  src/OnboardingSPA/components/StateHandlers/Design/index.js
  src/OnboardingSPA/steps/SiteGen/Editor/index.js
  src/OnboardingSPA/steps/SiteGen/Preview/index.js
Labels: Ready to merge

#530 Sitegen: Refactor Error State
  src/OnboardingSPA/components/App/index.js
  src/OnboardingSPA/components/ErrorState/Step/SiteGen/contents.js
  src/OnboardingSPA/components/ErrorState/Step/SiteGen/index.js
  src/OnboardingSPA/components/ErrorState/Step/SiteGen/stylesheet.scss
  src/OnboardingSPA/components/Header/components/SiteGenHeader/step-navigation.js
  src/OnboardingSPA/components/ImageUploader/components/ImageUploaderWithText/index.js
  src/OnboardingSPA/components/ImageUploader/components/ImageUploaderWithText/utils.js
  src/OnboardingSPA/components/Loaders/SiteGenLoader/index.js
  src/OnboardingSPA/components/NewfoldInterfaceSkeleton/SiteGen/index.js
  src/OnboardingSPA/components/StateHandlers/SiteGen/contents.js
  src/OnboardingSPA/components/StateHandlers/SiteGen/index.js
  src/OnboardingSPA/components/StateHandlers/index.js
  src/OnboardingSPA/steps/SiteGen/Experience/index.js
  src/OnboardingSPA/steps/SiteGen/Preview/index.js
  src/OnboardingSPA/steps/SiteGen/SiteDetails/index.js
  src/OnboardingSPA/steps/SiteGen/SiteLogo/index.js
  src/OnboardingSPA/steps/SiteGen/SocialMedia/index.js
  src/OnboardingSPA/store/actions.js
  src/OnboardingSPA/store/reducer.js
  src/OnboardingSPA/store/selectors.js
  src/OnboardingSPA/styles/app.scss
  src/OnboardingSPA/utils/api/siteGen.js
Labels: Ready to merge

#532 A/B test for AI Site Generation
  includes/RestApi/EventsController.php
  includes/Services/EventService.php
  src/OnboardingSPA/components/StartOptions/contents.js
  src/OnboardingSPA/components/StartOptions/index.js
  src/OnboardingSPA/components/StartOptions/stylesheet.scss
  src/OnboardingSPA/steps/TheFork/contents.js
  src/OnboardingSPA/steps/TheFork/index.js
  src/OnboardingSPA/utils/analytics/hiive/OnboardingEvent.js
  src/OnboardingSPA/utils/analytics/hiive/constants.js
  src/onboarding.js
  tests/cypress/integration/5-AI-SiteGen-onboarding-flow/1-fork.cy.js
Labels: Ready to merge

#537 Fix DIY theme change modal showing up in Sitegen Flow
  src/OnboardingSPA/components/StateHandlers/Design/index.js
  src/OnboardingSPA/steps/SiteGen/Preview/index.js
Labels: Code Review

#534 Add Tests for SiteGen Editor Step
  build/2.1.9/619.js
  src/OnboardingSPA/steps/SiteGen/Preview/index.js
  tests/cypress/fixtures/customize-data.json
  tests/cypress/fixtures/theme-style.json
  tests/cypress/integration/5-AI-SiteGen-onboarding-flow/1-fork.cy.js
  tests/cypress/integration/5-AI-SiteGen-onboarding-flow/2-welcome.cy.js
  tests/cypress/integration/5-AI-SiteGen-onboarding-flow/3-site-details.cy.js
  tests/cypress/integration/5-AI-SiteGen-onboarding-flow/4-site-logo.cy.js
  tests/cypress/integration/5-AI-SiteGen-onboarding-flow/5-experience.cy.js
  tests/cypress/integration/5-AI-SiteGen-onboarding-flow/6-preview.cy.js
  tests/cypress/integration/5-AI-SiteGen-onboarding-flow/7-editor.cy.js
  tests/cypress/integration/wp-module-support/MockApi.cy.js
Labels: Code Review

#542 Update `Readme.md`
  README.md
Labels: Code Review

#539 Switch to Fresh Installation check before activating Wonder Theme
  composer.json
  composer.lock
  includes/LoginRedirect.php
  src/OnboardingSPA/components/Button/NavCardButton/index.js
  src/OnboardingSPA/components/Header/components/SiteBuildHeader/step-navigation.js
  src/OnboardingSPA/components/StateHandlers/Design/contents.js
  src/OnboardingSPA/components/StateHandlers/Design/index.js
  src/OnboardingSPA/store/actions.js
  src/OnboardingSPA/store/selectors.js
Labels: QA

#540 Transfer Relevant Translations to Onboarding Data
  languages/wp-module-onboarding-pt_BR-nfd-onboarding.json
  languages/wp-module-onboarding-pt_BR.mo
  languages/wp-module-onboarding-pt_BR.po
  languages/wp-module-onboarding.pot
Labels: Ready to merge
