Repository newfold-labs/wp-module-onboarding, pull requests merged in 2025-03, with the labels that each got.

#665 Fix Font Family Issues
  src/OnboardingSPA/components/Sidebar/components/Customize/DesignFontsPanel/index.js
Labels: In Progress

#658 add site title and description to flow data
  src/OnboardingSPA/components/NewfoldInterfaceSkeleton/SiteGen/index.js
Labels: QA

#663 Change Editor Sidebar Loading State
  src/OnboardingSPA/steps/SiteGen/Editor/Sidebar/Customize/index.js
  src/OnboardingSPA/steps/SiteGen/Editor/stylesheet.scss
Labels: Code Review

#664 Fix Button Colors
  src/OnboardingSPA/steps/SiteGen/Editor/Header/index.js
  src/OnboardingSPA/steps/SiteGen/Editor/Header/stylesheet.scss
Labels: In Progress

#653 Fixing Live Previews
  includes/WP_Admin.php
  package.json
  src/OnboardingSPA/utils/global-styles/get-block-css-selector.js
  src/OnboardingSPA/utils/global-styles/use-global-styles-output.js
  src/OnboardingSPA/utils/global-styles/utils.js
Labels: QA

#660 Remove DIY from Fork
  src/OnboardingSPA/components/StartOptions/index.js
  src/OnboardingSPA/steps/TheFork/contents.js
  src/OnboardingSPA/steps/TheFork/index.js
  src/OnboardingSPA/utils/analytics/hiive/constants.js
  src/onboarding.js
  tests/cypress/integration/5-AI-SiteGen-onboarding-flow/1-fork.cy.js
Labels: Code Review

#670 Fix Live Preview Override
  src/OnboardingSPA/utils/global-styles/use-global-styles-output.js
Labels: QA

#672 Fix Light mode Button Colors
  src/OnboardingSPA/components/Button/NextButtonSiteGen/stylesheet.scss
  src/OnboardingSPA/steps/SiteGen/SiteDetails/stylesheet.scss
  src/OnboardingSPA/styles/_branding.scss
Labels: Code Review

#671 Clear Data for Onboarding Restart
  includes/Services/StatusService.php
  tests/cypress/fixtures/flow.json
  tests/cypress/integration/3-ecommerce-onboarding-flow/sitetype-primary.cy.js
  tests/cypress/integration/5-AI-SiteGen-onboarding-flow/6-preview.cy.js
  tests/cypress/integration/5-AI-SiteGen-onboarding-flow/7-editor.cy.js
  tests/cypress/integration/wp-module-support/MockApi.cy.js
Labels: Code Review

#677 Maintain state with Theme refresh
  includes/Services/StatusService.php
Labels: Code Review
